### ISSUE TITLE
Unexpected behaviour of middle column

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#808] opened 2016-08-08 10:55 UTC
![image](https://cloud.githubusercontent.com/assets/18674205/17477666/dcbfb14c-5d66-11e6-9720-edf13a5fe916.png)
If I click on the ">"-sign of the middle column to make the middle column disappear behind the the right column, but then both columns disappeared.

**Comment by literarymachine** [comment] 2016-08-08 11:55
Duplicate of #776. Closing.

**Closed by literarymachine** 2016-08-08 11:55 UTC
Labels: bug, duplicate
