### ISSUE TITLE
Languages of a service as extra point in the input template

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#772] opened 2016-07-13 10:04 UTC
As @trugwaldsaenger also mentioned, it would be clearer to have the languages of a service as extra point in the input template. At the moment the language is connected to the website. This may be misleading because a website for a repository for example can be in English but there could be resources in other languages in the repository. The person entering the data to the world map could misunderstand the template and only chose English instead of choosing the languages of all resources.

**Comment by literarymachine** [comment] 2016-07-13 10:49
I believe this is simply a misleading label in the input form. The underlying data is as follows:

    "availableChannel" : [ {
        "serviceUrl" : "http://learn.openscout.net/",
        "availableLanguage" : [ "en", "nl", "it", "sl", "fr", "es", "sv", "da", "pt", "de" ]
      } ]

So maybe we should just rename "Website" to "Service Channel" or "Resources available via" (and perhaps add the `url` property if we really want an additional field for "Website".

**Comment by karindr** [comment] 2016-07-13 11:20
In my opinion "Website" is most easily to understand, but "Resources available via" may be also relatively clear.
I don't no the system behind, but isn't the language of a service an property of a service just like grade level and subject and should be treated in the template in the same way?

**Comment by literarymachine** [comment] 2016-07-13 11:23
We are following the `schema.org` data model here, at least with regards to the `availableChannel`. It may well be that a service has a website (describing it) and some other URL for the actual repository. What does @acka47 say?

**Comment by acka47** [comment] 2016-07-13 12:05
This is a duplicate of #604. I just talked to @karindr. There seem to be several misunderstandings here. I will try to make this clearer.

Following schema.org, @literarymachine  and I saw that one could say something about the Service channel and the languages it is provided in . We weren't thinking about actual resources then, even the licensing information wasn't provided then. With the labeling of "Website" we had in mind that people understand we are talking about the languages available for the UI. As far as I know this is how Elise and Katharina entered the data: looking at the languages available for the UI. 

At some point @trugwaldsaenger thought that this doesn't make sense from the users' point of view as they probably are looking for _resources_ in a specific language. Although I told @trugwaldsaenger how this should be used in https://github.com/hbz/oerworldmap/issues/604#issuecomment-206465570 he told @karindr to record the languages of the available resources in this section.

This leaves us with inconsistent data that doesn't satisfy any use case. How will we solve this? There are at least two possibilities:

1. Add languages of offered OER to languages of service UI.
  1. Add https://schema.org/inLanguage to the data model for type `Service`.
  2. Manually move the data @karindr has created in this field and retain data on UI language.
2. Only offer information on languages of offered OER.
  1. Replace `availableLanguage` by ''inLanguage` in the data model as well as in the data.
  2. Adjust the information entered by Elise and Katharina. 

If we agree that information about the service UI's languages isn't relevant, we might remove this altogether.

**Comment by literarymachine** [comment] 2016-07-13 12:19
> With the labeling of "Website" we had in mind that people understand we are talking about the languages available for the UI.

Interesting - this is not what I had in mind. For me it was always about the resources provided via the `availableChannel`.

**Comment by acka47** [comment] 2016-08-17 14:25
@trugwaldsaenger How should we proceed with this? I outlined two possible solutions in https://github.com/hbz/oerworldmap/issues/772#issuecomment-232335341. Is one of them ok for you or do you prefer a third variant?

**Comment by karindr** [comment] 2016-08-18 09:53
Two arguments for connecting the language to the resources:

It is relatively easy to find resources on a website in a foreign language you have to translate with google translate. But it is much more difficult to understand complete resources in foreign languages maybe including spoken information. Therefore the language of the resource is more relevant to people searching for resources.

Services (nearly) always will include resources in the language the website is written. Because of this the older entries won’t become wrong if we change the policy of referring to the language. They will be only incomplete. Changing the policy the other way (that we refer only to the website), the data entered by me get wrong.

**Comment by trugwaldsaenger** [comment] 2016-08-19 08:34
I would propose to proceed via solution 2:
> Only offer information on languages of offered OER.
    - Replace availableLanguage by ''inLanguage` in the data model as well as in the data.
    - Adjust the information entered by Elise and Katharina.

For me it was always obvious that the language of the ressource is much more important than the language of the website. I`m also pretty sure that Elise and Katharina used the field in this way, so I guess that there will be no need to adjust their data.

> The data so far was entered by Katharina according to this understanding, see e.g. https://oerworldmap.org/resource/urn:uuid:c5a55ba0-7f00-11e5-a636-c48e8ff4ea31 which lists a lot of languages that as far as I know don't refer to the actual content but to the interface. 

This is wrong. Within the mentioned example the many languages refer to "translated simulation", which means to the included resources, not to the language of the site:
https://phet.colorado.edu/en/simulations/translated

For me the language of the site is of minor importance. I would not object collecting it, if anyone would propose it, but I don`t think it is necessary.

**Comment by acka47** [comment] 2016-08-23 14:48
To do:

- [ ] Adjust schema, add `inLanguage`
- [ ] Add `inLanguage` to [edit template](https://github.com/hbz/oerworldmap/blob/master/public/mustache/ResourceIndex/Article/edit.mustache)
- [ ] Add label to [labels.properties](https://github.com/hbz/oerworldmap/blob/master/conf/labels.properties)
- [ ] Add description to [description.properties](https://github.com/hbz/oerworldmap/blob/master/conf/descriptions.properties)
- [ ] add `inLanguage` property for uses of `availableLanguage` in triple store data
- [ ] Update filter function & label
- [ ] Remove `availableLanguage` from schema.json,  [edit template](https://github.com/hbz/oerworldmap/blob/master/public/mustache/ResourceIndex/Article/edit.mustache), [labels.properties](https://github.com/hbz/oerworldmap/blob/master/conf/labels.properties) and [description.properties](https://github.com/hbz/oerworldmap/blob/master/conf/descriptions.properties)
- [ ] Remove `availableLanguage` triples from triple store

**Comment by acka47** [comment] 2016-08-23 14:54
I just needed to try put the patch mechanism. Regarding
> add `inLanguage` property for uses of `availableLanguage` in triple store data

this patch should do it: https://oerworldmap.org/sparql/update?delete=&insert=%3Fresource+%3Chttp%3A%2F%2Fschema.org%2FinLanguage%3E+%3Flang&where=%3Fresource+%3Chttp%3A%2F%2Fschema.org%2FavailableChannel%3E+%3Fchannel+.+%3Fchannel+%3Chttp%3A%2F%2Fschema.org%2FavailableLanguage%3E+%3Flang+.

Thanks again for the great patch function, @literarymachine . (One improvement would be great: It would be great to have a larger `WHERE` window with two or three lines.)

**Comment by acka47** [comment] 2016-08-24 11:51
Looking at the schema, I suggest removing `availableChannel` and the associated `ServiceChannel` object altogether and use `inLanguage` and `url` instead. The example:

```json
"availableChannel" : [ {
    "serviceUrl" : "http://learn.openscout.net/",
    "availableLanguage" : [ "en", "nl", "it", "sl", "fr", "es", "sv", "da", "pt", "de" ]
  } ]
```

would at the end look like this:

```json
    "url" : "http://learn.openscout.net/",
    "inLanguage" : [ "en", "nl", "it", "sl", "fr", "es", "sv", "da", "pt", "de" ]
```

What do you think, @literarymachine ? If you agree, I would work on both in this issue as these are interrelated.

**Comment by acka47** [comment] 2016-08-24 12:38
Here is an updated version of the to do list for exchanging both `serviceURL` and `availableLanguage`.  I also adjusted the order a bit:

- [ ] Adjust schema.json, add `inLanguage` & `url` to Service
- [ ] Remove [ServiceChannel](https://github.com/hbz/oerworldmap/blob/master/public/mustache/ResourceIndex/ServiceChannel/edit.mustache) and the associated labels and descriptions from [labels.properties](https://github.com/hbz/oerworldmap/blob/master/conf/labels.properties) and [description.properties](https://github.com/hbz/oerworldmap/blob/master/conf/descriptions.properties) 
- [ ] Add `inLanguage` & `url` to [edit template](https://github.com/hbz/oerworldmap/blob/master/public/mustache/ResourceIndex/Service/edit.mustache), [labels.properties](https://github.com/hbz/oerworldmap/blob/master/conf/labels.properties) and [description.properties](https://github.com/hbz/oerworldmap/blob/master/conf/descriptions.properties)
- [ ] Duplicate uses of `availableChannel`/`availableLanguage`/`serviceURL` with `inLanguage`/`url`in triple store

___

- [ ] Update filter function & label
- [ ] Remove `availableChannel`/`availableLanguage`/`serviceURL` from schema.json
- [ ] Remove `availableChannel`/`availableLanguage`/`serviceURL`  triples from triple store

I can savely work on the first four bullet points and make a pull request. When the filter function is also updated we can deply it and then adjust the schema and remove the old data.

**Comment by acka47** [comment] 2016-09-22 13:01
@literarymachine As the data model changes won't be implemented soon, please go ahead and restructure the input template. I had a look at the files but couldn't figure out how to adjust this so I won't do it myself. Moving to ready.

**Comment by acka47** [comment] 2016-09-22 13:09
To be more concrete regarding the restructuring:

- Use "URL" instead of Website (tool tip: "The URL of the service")
- Add another paragraph "Languages" with the drop down to choose languages. (tool tip: "Languages of the resources offered by the service"

**Comment by literarymachine** [comment] 2016-09-22 13:53
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:aafaf915-c99f-4b26-82ef-8befbdf46867

**Comment by acka47** [comment] 2016-09-22 13:56
+1

**Closed** 2016-09-22 14:02 UTC
Labels: enhancement, review

**Comment by trugwaldsaenger** [comment] 2016-09-23 07:46
+1
