### ISSUE TITLE
Sometimes the search field and the selection bar get lost …

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#677] opened 2016-06-01 10:59 UTC
… behind the right column, see:
http://oerworldmap.graphthinking.com/country/fr
I think it should be displayed in the middle.

**Comment by karindr** [comment] 2016-06-02 10:53
Same, when the country infos are displayed in the middle
http://oerworldmap.graphthinking.com/country/de#urn:uuid:a11f0556-d2c8-4d18-adc4-61c6f9d8dd74
Maybe in this case the search area should be displayed in the left column.

**Comment by j0hj0h** [comment] 2016-06-02 18:24
This is not a bug. Currently the country views are kind of an alternative to the index-column (with the search and filter section). We already discussed an alternative solution where the country view sits on top of the search and filter section. As far as I know we planned this for the third quarter.

**Comment by trugwaldsaenger** [comment] 2016-06-20 08:09
Added this to our roadmap: https://wiki1.hbz-nrw.de/display/OWM/Roadmap+phase+III+%282016%29
Should we rename the issue, so that is is more easy to understand. I named it "reposition country view in navigation", but there might be better names...

**Comment by literarymachine** [comment] 2016-07-01 09:25
Fixed by b3cb14af3b836ed40ea784868eb46b445e7e588f

**Closed by literarymachine** 2016-07-01 09:25 UTC
Labels: bug, deploy, v1.1
