### ISSUE TITLE
Relation between map and search result list not working for country views

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#581] opened 2016-03-08 19:59 UTC
Normally the displayed pins on the map should be reflected by the search result list. For every pin there should be an entry in the search result and if you mouse over this entry, the related pin gets highlighted.

This relation is not working when starting to browse using a country view. When you click on a country and then start clicking on the aggregated pins, there seems to be no relation at all. The search result list does not change, no matter if the complete country is displayed or only a small number of pins.

**Comment by literarymachine** [comment] 2016-03-08 22:21
> Normally the displayed pins on the map should be reflected by the search result list. For every pin there should be an entry in the search result and if you mouse over this entry, the related pin gets highlighted.

Until now, it has only been the other way around. While the search result list is reflected by the pins, zooming in and out of the map has no effect on the search result list. We have been thinking about implementing this behavior with the shift to #577; nevertheless, this is not a bug but an enhancement / a new feature.

**Comment by literarymachine** [comment] 2016-03-08 22:23
@trugwaldsaenger If this of high priority, please let use know.

**Comment by acka47** [comment] 2016-03-09 16:00
Currently, I don't see any pins on the country view e.g. for Germany: https://oerworldmap.org/country/de

**Comment by literarymachine** [comment] 2016-03-09 17:49
> Currently, I don't see any pins on the country view e.g. for Germany: https://oerworldmap.org/country/de

Country listings are back as of 4f6bc655d1e6cc0ab4a8c9b50095e2a41cffe6b5, see https://github.com/hbz/oerworldmap/pull/587#issuecomment-194417625.

**Comment by literarymachine** [comment] 2016-03-10 10:36
> Currently, I don't see any pins on the country view e.g. for Germany: https://oerworldmap.org/country/de

@acka47 Can you confirm this is fixed on beta?

**Comment by acka47** [comment] 2016-03-10 15:01
Missing pins in country view are now fixed on beta and production. +1

**Comment by literarymachine** [comment] 2016-04-05 13:49
@philboeselager: Could you integrate [Geo Bounding Box Query](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-geo-bounding-box-query.html) into our Elasticsearch Repo? Not sure how it is best done, perhaps by also adding something to the QueryContext?

**Comment by philboeselager** [comment] 2016-04-05 14:59
@literarymachine : Yes, I am gonna do that. Did you take into account that ideally, while searching over countries' entries, we should use [Geo Polygon Query](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-geo-polygon-query.html) ? On the other hand side, the clear drawback of (pure) Polygon Query is performance. It is commonly recommended to prepend Polygon Query by a (wrapped) Bounding Box Query.

It seems like we should implement both functionalities:
A) Bounding Box for zoom results
B) Polygon for country-specific results

Both, A and B, can be realized via QueryContext - where the combination of both functionalities (zooming into a country-specific map and get the appropriate search results) gets a bit tricky, especially with consideration of the zooming history. But possible anyway.

I am gonna start by implementing Bounding Box Query and subsequently add Polygon Query. Do you agree?

**Comment by literarymachine** [comment] 2016-04-05 15:22
> It seems like we should implement both functionalities:
> A) Bounding Box for zoom results
> B) Polygon for country-specific results

B) is currently handled by simply filtering on `location.address.addressCountry`, which works fine and probably performs better. But I agree that we should also have polygon queries nevertheless, especially once we get into sub national divisions e.g. for #327.

Once the functionality is available, we should also take #479 into account here, because we have to get the the polygons from somewhere.

**Comment by philboeselager** [comment] 2016-04-08 08:06
Is finished from the backend side. Frontend plan is to:

- insert a helper button as a workaround for now
- have fully integrated behaviour with the release of the new UI (in May 2016)

**Comment by acka47** [comment] 2016-07-21 09:25
Looks like its working now. Closing.

**Comment by acka47** [comment] 2016-07-21 09:29
Misunderstanding from my side. Reopening.

**Comment by literarymachine** [comment] 2016-11-15 16:08
On beta, see e.g. https://beta.oerworldmap.org/resource/?filter.about.@type=Organization and zoom into the map.

**Comment by acka47** [comment] 2016-11-15 18:48
+1 The list adjusts very quickly to zooming in and out. Nice!

**Comment by karindr** [comment] 2016-11-16 08:27
It seems to work correct. But there is one irritating thing: If you click on an aggregated pin in a country view the map zooms in and the pin is resolved as it should but the text above the new search results is still, for example: “Found 2 entities for France ...”. My understanding is that this is not correct, because ist does no longer describes the results of France (which are 16 entities).

**Comment by acka47** [comment] 2016-11-16 08:36
Yes, this is not good. When you not go via a country view it reads "Found x entities". That also is not the best phrasing. I think the easiest way to resolve this is to replace "“Found x entities for France" as well as Found x entities" by "x entries shown".

Note that I propose "entries" instead of "entities" as I think that most users will easily understand it – which i don't think holds for "entities".

**Comment by trugwaldsaenger** [comment] 2016-11-16 08:40
It seems as if the original issue has not been solved yet: 

If I set a filter on Germany, I get a list of all entries from Germany. If I mouseover this list I see the according pins flashing in orange. 

If I do the same starting with the country view of Germany, I can mouseover the list and no pins are highlighted.

**Comment by literarymachine** [comment] 2016-11-16 09:40
> If I do the same starting with the country view of Germany, I can mouseover the list and no pins are highlighted.

Sorry, obviously misunderstood the issue. Fixed on beta, see e.g. https://beta.oerworldmap.org/country/de

> I think the easiest way to resolve this is to replace "“Found x entities for France" as well as "Found x entities" by "x entries shown".

On https://beta.oerworldmap.org

**Comment by acka47** [comment] 2016-11-16 09:46
:+1:

**Comment by acka47** [comment] 2016-11-16 09:52
@literarymachine BTW, is there any chance we can easily make the current view of a map (with zoom and corresponding result list) linkable so that I can send it to someone else? I guess we already talked about this but don't recall what kind of effort is needed to implement it...

**Comment by trugwaldsaenger** [comment] 2016-11-16 10:58
+1 thanks for the quick solution!

**Closed** 2016-11-16 16:07 UTC
Labels: deploy, enhancement
