### ISSUE TITLE
When hiding the text column the selection you made disappears

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1201] opened 2017-05-08 08:26 UTC
When you are i.e. on the German country view and click on the button with the little arrow to hide the text column the map changes back to the whole world with no country chosen. This behaviour is the same for every filter or search term search. For me this behaviour feels like a bug, I only wanted the column to disappear to see more of the map. What do you think?

**Comment by karindr** [comment] 2017-05-08 08:44
Interestingly the selection comes back when you log in! This behaviour is definitively a bug either the selection is gone or it is not gone.

**Comment by formimkontext** [comment] 2017-05-16 14:13
This is not a bug, but a conceptual imprecision. Hiding the column shouldn’t clear the filter. Closing the column should. I thought we allready discussed this, but couldn’t find any notes. We definitely have to discuss this.

**Comment by j0hj0h** [comment] 2017-05-19 09:25
Decision:
- Index column will be "closable" by a new X, which will replace the "clear filter" link
- Index column will be "collapsable" by the current arrow
- Detail column will only be "closable" by a new X

**Comment by dobladov** [comment] 2018-08-01 16:17
Fixed in the new UI.

**Closed by dobladov** 2018-08-01 16:17 UTC
Labels: enhancement
