### ISSUE TITLE
Licence of the OER World Map is hard to find

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1306] opened 2017-07-26 11:26 UTC
I just entered the OER World Map as service since it is the example for this in the FAQ for editors and I realised that the licence of the provided information is hard to find. Why not put a cc-Icon on the website?

**Comment by acka47** [comment] 2017-07-26 12:20
This might be a duplicate of #628 (if you are referring to the data license).

**Comment by karindr** [comment] 2017-07-26 12:52
In some kind it may be. 

I think it would be useful to have the CC-0 and under the stories the CC-By licence logo shown on the map.

**Closed** 2018-10-17 15:55 UTC
Labels: P3 - Could, enhancement
