### ISSUE TITLE
Order subjects on service profile hierarchical

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#745] opened 2016-07-05 13:47 UTC
![subjects](https://cloud.githubusercontent.com/assets/6639965/16586706/79c91e48-42c7-11e6-8365-4eab2a44760e.JPG)
Subjects should be ordered according to their hierarchy. In the example I guess it should be:
- Arts and humanities
- Languages
- Language acquisition
- Language acquistion\u2013 German

**Comment by karindr** [comment] 2016-07-06 10:01
This would be a really useful enhancement! See also #626.

**Comment by literarymachine** [comment] 2016-12-05 17:50
Duplicate of #626, closing.

**Closed by literarymachine** 2016-12-05 17:50 UTC
