### ISSUE TITLE
global statistics table is lost

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#681] opened 2016-06-02 11:06 UTC
Up to version 1.1 we had a table displaying the number of all contents included in the Map on the homepage.
![statistic-table](https://cloud.githubusercontent.com/assets/6639965/15742904/029333a0-28c2-11e6-8e1f-4484a18ab579.JPG). 
This table is lost in the new version, probably, because with the new layout its original location was lost. I think the tabel gave important infomation, showing the users at one sight, what kind of data and how much data is included in the system. I would therefore include the tabele again. But I`m not 100% sure, where to include it best. Right now I would propose to include it in the diagram column over the pie charts and maybe also in the introduction message, which is shown when looking at the World Map for the first time.

**Comment by j0hj0h** [comment] 2016-06-03 16:27
The table is not lost, as it wasn't intended to be present in the new version as far as I remember. I'd suggest to wait until the new filtersection and statistic column are ready as i tink both together are a good replacement. The filtersection introduces the icons, which will show the names when hovered and the pie charts in the statistic column will have labels and could also be enriched with absolute numbers. So all the information will be there.

**Comment by trugwaldsaenger** [comment] 2016-06-06 08:55
I cannot remember that we actively decided to keep it out, but I might be wrong here. I think the important point is that the new three column layout (which by the way is awesome) has no "homepage" any longer. I think we discussed this issue during our last meeting in Berlin without coming to a final solution. So we should keep in mind, that some place for messages and highlights would be helpful. What comes closest to this is the introduction page. But right now it is not a fully adequate page, since it has to be clicked away and cannot be activated again. Practically I agree with you that it is a good idea to look at this issue after we included the new filter section, so for V1.1 it is of low priority!

**Comment by literarymachine** [comment] 2016-06-08 12:41
@j0hj0h and I assumed that the designs in https://github.com/hbz/oerworldmap/issues/577#issuecomment-200319919 have been agreed upon. As for #682, maybe @formimkontext can come up with something.

**Comment by j0hj0h** [comment] 2016-06-08 17:01
I'd already have an idea how to show the info from this table in the new welcome notification and I'm sure I could develop something nice with @formimkontext. Concerning the need for a place for "messages and highlights" @trugwaldsaenger mentioned: the new notifications can be used very flexible and there could be additional notifications when we have news, that should be shown to everybody comming to the page.
But together with the question where and how to show recent additions (also discussed during the last meeting), this is something which is on the one hand easier to discuss face-to-face and on the other better to estimate, when the filter section and statistic column are ready.

**Comment by philboeselager** [comment] 2016-06-21 12:14
This is not a bug, like #682 .

**Comment by literarymachine** [comment] 2016-07-01 09:30
Fixed by #701

**Closed by literarymachine** 2016-07-01 09:30 UTC
Labels: bug, deploy, v1.1
