### ISSUE TITLE
Likes and lighthouses disfunctional

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1702] opened 2018-11-13 15:38 UTC
I just tried to like an entry as well as to set a lighthouse. Both actions did not work. The "like" buttom did not get organge and I was unable to save my lighthouse-comment. I tried to do so using both Firefox and Chrome.

**Comment by literarymachine** [comment] 2018-11-13 15:48
Yep, confirmed. This is due to https://github.com/hbz/oerworldmap/issues/1673 which I have just deployed. So suddenly, `description` and `url` are mandatory. When liking or lighthousing an entry, we are updating it. If it has no `desciption` or `url`, it fails.

**Comment by literarymachine** [comment] 2018-11-13 15:52
@trugwaldsaenger please always provide as much context as possible. In this case: which entry did you try to like?

**Comment by trugwaldsaenger** [comment] 2018-11-13 15:59
This is the entry I tried to like: https://oerworldmap.org/resource/urn%3Auuid%3Ae0198a84-666b-44cb-b321-176c1d5ca736?

**Comment by dobladov** [comment] 2018-11-26 09:59
Related: https://github.com/hbz/oerworldmap/issues/1397

**Comment by literarymachine** [comment] 2018-11-26 16:15
Fixed in #1703

**Closed by literarymachine** 2018-11-26 16:15 UTC
Labels: bug
