### ISSUE TITLE
Policy title not shown in policy registry

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1852] opened 2019-07-26 14:07 UTC
![image](https://user-images.githubusercontent.com/777278/61957338-57503780-afbf-11e9-8021-8213c5ef8391.png)

https://oerworldmap.org/oerpolicies

**Comment by literarymachine** [comment] 2019-07-29 08:34
Duplicate of #1848, closing.

**Closed by literarymachine** 2019-07-29 08:34 UTC
