### ISSUE TITLE
Add second levels to existing entries

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1544] opened 2018-05-18 07:11 UTC
As @literarymachine pointed out correctly it does not make sense to display the second level navigation, if there is no content available for them. This is a potentially huge editorial working package. For Germany we could include second levels for services automatically, since we have used tags here (e.g. servicetype:service), but we still have to discuss, if this makes sense. Also persons will have to add the second level categories for their profiles by themselves. A good starter would be to concentrate on services first and than proceed stepwise.

**Comment by literarymachine** [comment] 2018-05-23 14:11
> For Germany we could include second levels for services automatically, since we have used tags here (e.g. servicetype:service)

Here is a list of the service type keywords currently in use: https://oerworldmap.org/resource/?filter.about.%40type=Service&q=about.keywords:servicetype\:*

The tags used are:

```
servicetype:mooc platform
servicetype:other
servicetype:tutorial&courses
servicetype:repository
servicetype:referatory
servicetype:information&reflection
servicetype:textbook
servicetype:encyclopedia
servicetype:youtubechannel
servicetype:authoringtool
servicetype:wiki
servicetype:contentsource
servicetype:learning-platform
servicetype:community
```

Not all of them map to a second level classification in our current draft.

**Comment by trugwaldsaenger** [comment] 2018-06-05 09:44
@acka47 was so kind to define a search filter for all entries, which do not have a subtype yet:

https://oerworldmap.org/resource/?q=NOT%20_exists_%3Aabout.additionalType&features=true&map=60.10915%2C73.21743%2C5

It`s very easy to work with this. Simple activate and than go through the list one by one...

**Comment by literarymachine** [comment] 2018-06-05 10:11
> It`s very easy to work with this. Simple activate and than go through the list one by one...

Given that `2779` of `2837` entries don't have an `additionalType`, this is of limited use I would argue. I still think we should first try to migrate those cases where certain tags can be mapped to our categories, e.g. [`servicetype:*`](https://oerworldmap.org/resource/?filter.about.@type=Service&q=about.keywords:servicetype\\:*). Are there others? What do we do with those that don't map, see https://github.com/hbz/oerworldmap/issues/1544#issuecomment-391361789?

**Comment by literarymachine** [comment] 2018-06-05 10:16
>  Are there others?

To answer my own question, it does not seem so: https://oerworldmap.org/sparql/query?q=SELECT+DISTINCT+%3Fkeyword+WHERE+%7B%0D%0A++%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%3Fkeyword+.%0D%0A++FILTER+regex%28%3Fkeyword%2C+%22.*type.*%22%2C+%22i%22%29%0D%0A%7D

**Comment by trugwaldsaenger** [comment] 2018-06-05 11:52
servicetype:mooc platform = "content source"
servicetype:other = "other"
servicetype:tutorial&courses = "information, reflection & tutorials"
servicetype:repository = "repository"
servicetype:referatory = "referatory"
servicetype:information&reflection = "information, reflection & tutorials"
servicetype:textbook = "content source"
servicetype:encyclopedia = "content source"
servicetype:youtubechannel = "content source"
servicetype:authoringtool = "authoring tool"
servicetype:wiki = "content source"
servicetype:contentsource = "content source"
servicetype:learning-platform = "learning platform"
servicetype:community = "community platform"

**Comment by trugwaldsaenger** [comment] 2018-06-05 11:59
In order to keep the list short I did not take

- mooc platform (better: provider)
- textbook (better: textbook collection)
- youtube channel (better: video channel)
- encyclopedia

Into the list. Nevertheless I think these are rather clear categories and the total number still will be smaller than the subcategories of the organizations. I therefore would argue to include. @acka47: Any concerns about this?

**Comment by trugwaldsaenger** [comment] 2018-06-05 12:22
> Given that 2779 of 2837 entries don't have an additionalType, this is of limited use I would argue. I still think we should first try to migrate those cases where certain tags can be mapped to our categories,

I´m happy if you can do the migration automatically. I think last time we spoke about this, you were not sure how big the effort was. Nevertheless, this will not solve our problems entirely. After the migration approximatly 2650 entries will remain without subcategory. But I don`t think it`s that bad for several reasons:

- 460 are persons, so we cannot do it ourselves anyway
- we could consider giving every organisation, which has the word "university" in its name the subtype "higher education institution"
- We can ask the community via one of the upcoming newsletter to help us - I think it will be worth a try
- 60 already have be done - without major effort, so if @karindr and me work on this for two days systematically, we will manage to do a lot
- If not every entry gets a subtype, this will be no major problem

**Comment by literarymachine** [comment] 2018-06-05 12:36
> I think last time we spoke about this, you were not sure how big the effort was.

I was referring to finding and documenting the mapping of keywords to categories. If a list like the one you created exists, migration is not a big issue!

> we could consider giving every organisation, which has the word "university" in its name the subtype "higher education institution"

This would solve the issue for [400 Organizations](https://oerworldmap.org/resource/?q=university&filter.about.%40type=Organization), great!

> If not every entry gets a subtype, this will be no major problem

I agree, we should only make sure that not too many links to sub categories in the new header lead to empty results.

**Comment by literarymachine** [comment] 2018-06-06 09:55
> This would solve the issue for 400 Organizations, great!

@acka47  this should be the migration for [Organizations that have `university` in their name and have no `additionalType` assigned yet](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Forganizations.json%23higherEducationInstitution%3E&where=%3Fs+a+%3Chttp%3A%2F%2Fschema.org%2FOrganization%3E+.+++%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fname+.+++FILTER+NOT+EXISTS+%7B+%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Forganizations.json%23higherEducationInstitution%3E+%7D+.+FILTER+regex%28%3Fname%2C+%22.*university.*%22%2C+%22i%22%29). Could you take a look just to make sure?

**Comment by acka47** [comment] 2018-06-06 11:17
It should read `FILTER NOT EXISTS { ?s <http://schema.org/additionalType> ?o }` instead of `FILTER NOT EXISTS { ?s <http://schema.org/additionalType> <https://oerworldmap.org/assets/json/organizations.json#higherEducationInstitution> }`

**Comment by literarymachine** [comment] 2018-06-06 11:22
> It should read FILTER NOT EXISTS { ?s <http://schema.org/additionalType> ?o } instead of FILTER NOT EXISTS { ?s <http://schema.org/additionalType> <https://oerworldmap.org/assets/json/organizations.json#higherEducationInstitution> }

Ok, do you want to carry out the [updated migration](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Forganizations.json%23higherEducationInstitution%3E&where=%3Fs+a+%3Chttp%3A%2F%2Fschema.org%2FOrganization%3E+.+++%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fname+.+++FILTER+NOT+EXISTS+%7B+%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Fcat+%7D+.+FILTER+regex%28%3Fname%2C+%22.*university.*%22%2C+%22i%22%29)? Keep in mind I won't be available until Monday in case something severely breaks ;)

**Comment by acka47** [comment] 2018-06-06 11:23
Will do

**Comment by acka47** [comment] 2018-06-06 12:57
Done. It is not yet reflected in the search results, though, see https://oerworldmap.org/resource/?filter.about.additionalType.@id=https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Forganizations.json%23higherEducationInstitution. But individual entries have changed, see e.g. https://oerworldmap.org/resource/urn%3Auuid%3A879fd170-e372-4dea-a873-9775d7f9e8bf

I applied the patch >1h ago so this is definitely too long for updating the search index. There probably was a problem with triggering the update...

**Comment by literarymachine** [comment] 2018-06-06 14:09
> There probably was a problem with triggering the update...

I just realized that migrations using SPARQL don't trigger the indexing mechanism. So the good new is that this is currently expected behavior. Triggered it manually now:

https://oerworldmap.org/resource/?filter.about.additionalType.@id=https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Forganizations.json%23higherEducationInstitution

and created #1570 to automate this.

The result is only 256 instead of 400 results. This is because in the SPARQL migration we (correctly) queried the name only for "university", in https://github.com/hbz/oerworldmap/issues/1544#issuecomment-394692836 I mistakenly queried all fields and thus had false hits in there.

**Comment by karindr** [comment] 2018-06-07 07:21
@trugwaldsaenger and I agreed that it would be great to have a simmilar automatic input for the "Primary educational sector" field for these entries. It should be "Higher Education" for all these universities.

**Comment by karindr** [comment] 2018-06-07 07:29
Finished Luxemburg (also regions and sectors). ;-)

**Comment by acka47** [comment] 2018-06-07 07:36
> @trugwaldsaenger and I agreed that it would be great to have a simmilar automatic input for the "Primary educational sector" field for these entries. It should be "Higher Education" for all these universities.

[This](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FprimarySector%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fsectors.json%23higherEd%3E&where=%3Fs+a+%3Chttp%3A%2F%2Fschema.org%2FOrganization%3E+.+++%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fname%3E+%3Fname+.+++FILTER+NOT+EXISTS+%7B+%3Fs+%3Chttp%3A%2F%2Fschema.org%2FprimarySector%3E+%3Fcat+%7D+.+FILTER+regex%28%3Fname%2C+%22.*university.*%22%2C+%22i%22%29) should be the patch accordingly, right @literarymachine?

**Comment by literarymachine** [comment] 2018-06-07 07:44
> This should be the according patch, right @literarymachine?

Looks good to me.

**Comment by acka47** [comment] 2018-06-07 08:17
Done, you probable have to manually trigger the index update again, @literarymachine.

**Comment by literarymachine** [comment] 2018-06-21 13:44
@acka47 here are the migrations for the mappings in https://github.com/hbz/oerworldmap/issues/1544#issuecomment-394680898:

- [servicetype:mooc platform = "content source"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23contentSource%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Amooc+platform%22)
- [servicetype:other = "other"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23other%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Aother%22)
- [servicetype:tutorial&courses = "information, reflection & tutorials"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23information%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Atutorial%26courses%22)
- [servicetype:repository = "repository"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23repository%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Arepository%22)
- [servicetype:referatory = "referatory"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23referatory%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Areferatory%22)
- [servicetype:information&reflection = "information, reflection & tutorials"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23information%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Ainformation%26reflection%22)
- [servicetype:textbook = "content source"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23contentSource%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Atextbook%22)
- [servicetype:encyclopedia = "content source"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23contentSource%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Aencyclopedia%22)
- [servicetype:youtubechannel = "content source"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23contentSource%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Ayoutubechannel%22)
- [servicetype:authoringtool = "authoring tool"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23authoringTool%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Aauthoringtool%22)
- [servicetype:wiki = "content source"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23contentSource%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Awiki%22)
- [servicetype:contentsource = "content source"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23contentSource%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Acontentsource%22)
- [servicetype:learning-platform = "learning platform"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23learningPlatform%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Alearning-platform%22)
- [servicetype:community = "community platform"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23communityPlatform%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Acommunity%22)

The queries currently *don't* include the deletion of the original keyword as we might need those if we want to further differentiate in the future, see https://github.com/hbz/oerworldmap/issues/1544#issuecomment-394682664.

**Comment by literarymachine** [comment] 2018-06-21 14:54
@acka47 btw, with eb47cd862dde1f0b028fa588994bd998eaf0cff4 the index should be correctly updated after a migration.

**Comment by acka47** [comment] 2018-06-27 12:29
I applied all the patches except these two:

- [servicetype:textbook = "content source"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23contentSource%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Atextbook%22)
- [servicetype:encyclopedia = "content source"](https://oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Chttps%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23contentSource%3E&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22servicetype%3Aencyclopedia%22)

@trugwaldsaenger, is the type "content source" really intended to be used with single publications like a textbook? I thought that it would be the source of multiple "contents", e.g. multiple text books, images etc.

**Comment by trugwaldsaenger** [comment] 2018-07-20 14:20
@acka47: You are right, "servicetype:textbook" is misleading. It was never meant to describe a single textbook, but rather a service focussing on textbooks, like a textbook collection!

**Comment by acka47** [comment] 2018-09-25 13:52
All patches have been applied. Closing.

**Closed by acka47** 2018-09-25 13:52 UTC
