### ISSUE TITLE
Including person description on Beta produces error

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#507] opened 2015-12-18 11:42 UTC
I copied a text into my personal description and received an error. As soon as I try to edit again, the error appears directly, so that working on my entry seems to be impossible now.

Following Error Message was provided.
The data you entered is invalid

We are working hard on better error reporting. But until that is done, you are unfortunately stuck with this:

com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: instance failed to match exactly one schema (matched 0 out of 2)
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action/properties/agent/items"}
    instance: {"pointer":"/agent/0"}
    domain: "validation"
    keyword: "oneOf"
    matched: 0
    nrSchemas: 2
    reports: {"/definitions/Action/properties/agent/items/oneOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/LocalizedString/items"},"instance":{"pointer":"/agent/0/description/0"},"domain":"validation","keyword":"required","message":"object has missing required properties ([\"@language\"])","required":["@language","@value"],"missing":["@language"]}],"/definitions/Action/properties/agent/items/oneOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/Organization"},"instance":{"pointer":"/agent/0"},"domain":"validation","keyword":"additionalProperties","message":"object instance has properties which are not allowed by the schema: [\"performerIn\"]","unwanted":["performerIn"]}]}
error: object has missing required properties (["@language"])
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/LocalizedString/items"}
    instance: {"pointer":"/description/0"}
    domain: "validation"
    keyword: "required"
    required: ["@language","@value"]
    missing: ["@language"]
error: object has missing required properties (["@language"])
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/LocalizedString/items"}
    instance: {"pointer":"/performer/0/description/0"}
    domain: "validation"
    keyword: "required"
    required: ["@language","@value"]
    missing: ["@language"]
error: instance failed to match exactly one schema (matched 0 out of 2)
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Event/properties/organizer/items"}
    instance: {"pointer":"/organizer/0"}
    domain: "validation"
    keyword: "oneOf"
    matched: 0
    nrSchemas: 2
    reports: {"/definitions/Event/properties/organizer/items/oneOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/LocalizedString/items"},"instance":{"pointer":"/organizer/0/description/0"},"domain":"validation","keyword":"required","message":"object has missing required properties ([\"@language\"])","required":["@language","@value"],"missing":["@language"]}],"/definitions/Event/properties/organizer/items/oneOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/Organization"},"instance":{"pointer":"/organizer/0"},"domain":"validation","keyword":"additionalProperties","message":"object instance has properties which are not allowed by the schema: [\"performerIn\"]","unwanted":["performerIn"]}]}
error: instance failed to match exactly one schema (matched 0 out of 3)
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Organization/properties/member/items"}
    instance: {"pointer":"/member/0"}
    domain: "validation"
    keyword: "oneOf"
    matched: 0
    nrSchemas: 3
    reports: {"/definitions/Organization/properties/member/items/oneOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/LocalizedString/items"},"instance":{"pointer":"/member/0/description/0"},"domain":"validation","keyword":"required","message":"object has missing required properties ([\"@language\"])","required":["@language","@value"],"missing":["@language"]}],"/definitions/Organization/properties/member/items/oneOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/Organization"},"instance":{"pointer":"/member/0"},"domain":"validation","keyword":"additionalProperties","message":"object instance has properties which are not allowed by the schema: [\"performerIn\"]","unwanted":["performerIn"]}],"/definitions/Organization/properties/member/items/oneOf/2":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/Service"},"instance":{"pointer":"/member/0"},"domain":"validation","keyword":"additionalProperties","message":"object instance has properties which are not allowed by the schema: [\"agentIn\",\"countryChampionFor\",\"organizerFor\",\"performerIn\",\"url\"]","unwanted":["agentIn","countryChampionFor","organizerFor","performerIn","url"]}]}
---  END MESSAGES  ---

{
  "image" : "https://oerworldmap.files.wordpress.com/2015/03/jan.jpeg?w=108&h=110",
  "countryChampionFor" : [ "DE" ],
  "@type" : "Person",
  "name" : [ {
    "@value" : "Jan Neumann",
    "@language" : "en"
  } ],
  "agentIn" : [ {
    "@id" : "urn:uuid:9286f1c6-b8db-4800-8f09-b12141b3310b"
  } ],
  "description" : [ {
    "@value" : "Jan (@trugwaldsaenger on twitter) is working as head of legal affairs and organisation at the North Rhine-Westphalian Library Service Centre in Cologne, Germany. He studied law, economy and systems thinking, is member of the educational advisory board of the German UNESCO chapter and blogs about OER on www.oersys.org. Currently he is the project manager of the OER World Map project."
  } ],
  "location" : {
    "geo" : {
      "lon" : 6.9355108,
      "lat" : 50.9340509
    },
    "address" : {
      "addressCountry" : "DE",
      "streetAddress" : "Jülicher Straße 6",
      "postalCode" : 50674,
      "addressLocality" : "Köln"
    }
  },
  "@id" : "urn:uuid:839897e6-178f-11e5-871b-3c970e4a9cbf",
  "memberOf" : [ {
    "@id" : "urn:uuid:7609a1b0-904b-4ed8-bb2b-48467ab09595"
  } ],
  "url" : "http://www.oersys.org/",
  "email" : "neumann@hbz-nrw.de",
  "sameAs" : [ "https://twitter.com/trugwaldsaenger"

**Comment by literarymachine** [comment] 2015-12-18 12:46
This is expected behavior. It is just a very long way of saying: you did not pick a language for your description:

    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/LocalizedString/items"}
    instance: {"pointer":"/description/0"}
    domain: "validation"
    keyword: "required"
    required: ["@language","@value"]
    missing: ["@language"]
    error: object has missing required properties (["@language"])

Like it says, we are working on better error reporting. Actually, when entering a text in a localized field such as `description`, English should automatically be selected as the language to reduce the likelihood of such errors; nevertheless, this is not a bug. Closing.

**Closed by literarymachine** 2015-12-18 12:46 UTC
Labels: bug

**Comment by literarymachine** [comment] 2015-12-18 12:47
> Actually, when entering a text in a localized field such as description, English should automatically be selected as the language

This currently only works when using the keyboard, you probably copy & pasted by mouse?
