### ISSUE TITLE
"Bad request" when entering url to story template in source field

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1648] opened 2018-09-17 08:35 UTC
I created a test-Story to test how the Citation field works.
https://oerworldmap.org/resource/urn%3Auuid%3A294f72b2-3cc5-4b7d-a847-37a010d6e0e2?

When I enter a URL and publish there is "Error Bad request" shown.
https://oerworldmap.org/resource/urn:uuid:294f72b2-3cc5-4b7d-a847-37a010d6e0e2

(BTW I started using Gramarly as a plugin for chrome, it works fine on most websites, for example here. It works fine. Can this cause this problem and the strange problems lately?)

**Comment by dobladov** [comment] 2018-09-17 08:45
Confirmed, the error occurs when we introduce any text into the field citation but not the title. I'm looking into it.

**Comment by literarymachine** [comment] 2018-09-17 09:51
@dobladov this is most likely a schema issue. @karindr could it be that no story has been added in a very long time? Because the schema has not changed.

**Comment by literarymachine** [comment] 2018-09-17 09:51
> Gramarly as a plugin for chrome, it works fine on most websites, for example here

I neither know what this is nor what it does.

**Comment by literarymachine** [comment] 2018-09-17 10:01
@karindr if you are investigating this for #1635, let me just add it to `Publication`. It is a very simple text field where you will be able to enter whatever (free text) citation information.

**Comment by literarymachine** [comment] 2018-09-17 10:04
As for this issue here, the `Bad request` is due to our quite complex schema for Stories, which unfortunately currently is not reflected correctly in the UI:

```
        "oneOf": [
            {
              "required": [ "license", "creator", "dateCreated" ]
            },
            {
              "required": [ "citation", "exampleOfWork" ]
            }
          ]
```

What this means is that you have to enter either a `license`, `creator` ("Author") and `dateCreated` or a `citation` and `exampleOfWork` ("Source"). We modeled it this way a long time ago; the use case for the first is a story that is originally published on the OER World Map, the use case for the latter a story that was originally published somewhere else.

**Comment by karindr** [comment] 2018-09-17 10:45
> It is a very simple text field where you will be able to enter whatever (free text) citation information.

If that means that we can write in this field something like "Additional authors: Felix O., Felix L. and Daniel D." and can get this text out of a column of the table to import this text, it is ok for me

**Comment by literarymachine** [comment] 2018-09-17 10:46
> If that means that we can write in this field something like "Additional authors: Felix O., Felix L. and Daniel D." and can get this text out of a column of the table to import this text, it is ok for me

It means this exactly, great!

**Comment by trugwaldsaenger** [comment] 2018-09-18 09:37
I looked at this story:
https://oerworldmap.org/resource/urn%3Auuid%3Ab6fcecc0-52e6-47f8-935c-38cf4528ab30?

After activating the editing modus, when trying to save the story again (without any changes), I´m asked to add a license. After adding the license information, I receive the error message "bad request".

**Comment by literarymachine** [comment] 2018-09-18 11:50
> As for this issue here, the Bad request is due to our quite complex schema for Stories, which unfortunately currently is not reflected correctly in the UI

Yes, the UI currently tries to enforce something that the API then does not validate. They are supposed to behave in the same way, e.g. reject or accept the same things, but in this special case they don't.

**Comment by literarymachine** [comment] 2018-09-18 13:47
> I looked at this story:
https://oerworldmap.org/resource/urn%3Auuid%3Ab6fcecc0-52e6-47f8-935c-38cf4528ab30?
> After activating the editing modus, when trying to save the story again (without any changes), I´m asked to add a license. After adding the license information, I receive the error message "bad request".

I deployed https://github.com/hbz/oerworldmap-ui/pull/385 to fix the conflicting UI / API validation problem. You can now save the above again. We will still have to come up with a UI solution for the *these fields are all required, and then either these or those other fields are also required, but exclusively, don't enter these **and** those fields* issue. Or we should think about a simpler schema.

**Comment by trugwaldsaenger** [comment] 2018-09-18 15:51
Thanks for moving this forward @literarymachine!

> We will still have to come up with a UI solution for the these fields are all required, and then either these or those other fields are also required, but exclusively, don't enter these and those other fields issue.

Sounds complicated. I just tried to add license information to the story and received a "should match exactly one schema in oneOf" error. Is this what you are referring to?

**Comment by literarymachine** [comment] 2018-09-18 16:17
> Sounds complicated. I just tried to add license information to the story and received a "should match exactly one schema in oneOf" error. Is this what you are referring to?

Yes, see https://github.com/hbz/oerworldmap/issues/1648#issuecomment-421952962.

**Comment by literarymachine** [comment] 2018-12-19 09:45
Fixed in https://github.com/hbz/oerworldmap/pull/1699

**Closed by literarymachine** 2018-12-19 09:45 UTC
Labels: bug
