### ISSUE TITLE
Blurry fonts on Win10/Chrome 

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1709] opened 2018-11-26 09:35 UTC
Example: https://oerworldmap.org/resource/?map=6.98288,50.93506,12

Chrome Version 70.0.3538.102, Win10 64-Bit
![image](https://user-images.githubusercontent.com/777278/49005196-6055e400-f166-11e8-9878-cd68c971d7f3.png)

Firefox seems fine
![image](https://user-images.githubusercontent.com/777278/49005294-a9a63380-f166-11e8-8b80-a8b35727584a.png)

**Comment by dobladov** [comment] 2018-11-26 09:54
Confirmed, this is a bug on mapbox-gl-js, the library we use for the map, unfortunately we can not fix this bug, they have two issues about it.

https://github.com/mapbox/mapbox-gl-js/issues/4906
https://github.com/mapbox/mapbox-gl-js/issues/3249

**Comment by dobladov** [comment] 2019-05-23 15:47
It seems to be closed by the updates.
Chrome
![chrome](https://user-images.githubusercontent.com/1938043/58266496-0aaf6c80-7d82-11e9-8a6b-7a314888228a.png)
Firefox
![ff](https://user-images.githubusercontent.com/1938043/58266499-0be09980-7d82-11e9-87b9-300916d84ac0.png)

**Closed by dobladov** 2019-05-23 15:47 UTC
