### ISSUE TITLE
Country filter influences search results

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1006] opened 2017-01-05 17:08 UTC
I just spoke with @philboeselager about this:

When I look for "OERinfo" I receive more than 480 hits. The good thing is that the first three are the most important ones:
1. The OERinfo project: https://oerworldmap.org/resource/?q=OERinfo#urn:uuid:efed6ca2-b228-480f-be03-090a19de7b42
2. The OERinfo start workshop: https://oerworldmap.org/resource/?q=OERinfo#urn:uuid:613a9621-a24d-4597-85f4-d1e8e53923e7
3. The OERinfo funding guidelines: https://oerworldmap.org/resource/?q=OERinfo#urn:uuid:3f11cdbd-a74a-4aa4-83b3-b4148bfdbe82

All three appear on the map, but only the startworkshop has a location of its own. The other ones receive the location from the operator. 

When I now set the country filter on Germany, the start workhop becomes the first hit, the other two (project and funding guideline) disappear.

**Comment by literarymachine** [comment] 2017-01-05 17:39
Duplicate of #996. As discussed there, I will re-index the data following the `agent` ("operator") property. We just have to make sure that when defining which relations should be traversed for the `location` we do not re-introduce #424.

**Comment by literarymachine** [comment] 2017-02-03 13:41
Fixed with #996, closing.

**Closed by literarymachine** 2017-02-03 13:41 UTC
Labels: duplicate, ready
