### ISSUE TITLE
Refine help text for dates

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#904] opened 2016-10-19 08:34 UTC
Propably the most commom reason for error messages is that the date is entered in the wrong format. To avoid this, the help text should be changed from "The start date of the event" into "The start date of the event in the format yyyy-mmy-dd". This has do be done for every date fields in the system.

**Comment by trugwaldsaenger** [comment] 2016-10-19 08:36
@acka47: Do I remember right, that you can change this things?

**Comment by acka47** [comment] 2016-10-19 09:00
Duplicate of #504 (for which there already is a fix on beta). Closing.

**Closed by acka47** 2016-10-19 09:00 UTC
Labels: enhancement
