### ISSUE TITLE
Add field fields "primary educational sector" and "secondary educational sector" to publications/policies

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1620] opened 2018-08-03 10:51 UTC

**Comment by karindr** [comment] 2018-08-23 09:10
Concerning publications duplicate of #1444

**Comment by trugwaldsaenger** [comment] 2018-09-05 12:48
@literarymachine: I expect this can be implemented easily - is this correct?
@karindr: We can add a collumn in our spreadsheet for this as well - alternatively we could add a tag...

**Closed** 2018-09-11 13:51 UTC
Labels: P1 - Must, review
