### ISSUE TITLE
Drop down menues in input template do not change language automatically

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#683] opened 2016-06-02 12:05 UTC
Normally the drop down lists in the input template should change their language according to the language of the used browser. On Version 1.1 this seems not to be activated yet - the drop downs (e.g. language) are displayed in English only.

**Comment by literarymachine** [comment] 2016-06-08 12:35
@j0hj0h this is a simple configuration issue, you need not worry about it!

**Comment by literarymachine** [comment] 2016-06-10 16:38
Configured on http://oerworldmap.graphthinking.com/

**Comment by karindr** [comment] 2016-06-13 10:49
Changed chrome to german but nothing changes.

**Comment by literarymachine** [comment] 2016-06-13 10:54
> Changed chrome to german but nothing changes.

What do you mean be "changed Chrome to German"? Language is controlled by an accept header, could you install https://chrome.google.com/webstore/detail/quick-language-switcher/pmjbhfmaphnpbehdanbjphdcniaelfie and try again?

![screenshot from 2016-06-13 12 53 26](https://cloud.githubusercontent.com/assets/149825/16005129/df15c9cc-3165-11e6-9fb4-39904419641d.png)
![screenshot from 2016-06-13 12 53 06](https://cloud.githubusercontent.com/assets/149825/16005130/df175706-3165-11e6-9bd7-ea764154d881.png)

**Comment by karindr** [comment] 2016-06-14 07:35
I changed the language by menu -> Einstellungen -> Erweiterte Einstellungen … -> Sprachen -> Sprach- und Eingabeeinstellungen. This doesn’t result in German drop down menus on production either. Strange. I installed the quick language switcher and even Chinese works.

On firefox all works fine.

On Jan’s computer it works fine on chrome and firefox now.

OK then.

**Comment by literarymachine** [comment] 2016-06-17 10:18
Closing this, since it is a configuration issue and not a bug.

**Closed by literarymachine** 2016-06-17 10:18 UTC
Labels: bug, v1.1
