### ISSUE TITLE
"Add language" should not be related to the website of a service

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#604] opened 2016-04-06 14:55 UTC
Our data model allows to add the language of the resources provided by a service. The field is available within the template, but it is directly placed after the field wich allows to input a link to the website. By doing so users must believe that the language refers to the website, not to the provided language of the ressources. I would propose to display the field seperatly and name it "Resource language" or similar.
![unbenannt](https://cloud.githubusercontent.com/assets/6639965/14321179/69f6315e-fc18-11e5-918f-947d78d54475.JPG)

**Comment by acka47** [comment] 2016-04-06 17:01
In our data model we use the property http://schema.org/availableLanguage which is described as "A language someone may use with the item [i.e. the Service]." IMO, this actually applies to the language of the service and not to the language of the content provided by the service. The data so far was entered by Katharina according to this understanding, see e.g. https://oerworldmap.org/resource/urn:uuid:c5a55ba0-7f00-11e5-a636-c48e8ff4ea31 which lists a lot of languages that as far as I know don't refer to the actual content but to the interface. 

For indicating the language of the content, we might (aditionally?) use https://schema.org/inLanguage.

**Comment by acka47** [comment] 2016-08-17 14:26
Closing this one as we this is a duplicate of #772 where most of the discussion happened.

**Closed by acka47** 2016-08-17 14:26 UTC
