### ISSUE TITLE
Strange behavior of the address field of organizations template

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1639] opened 2018-09-04 09:42 UTC
When I paste a copied address to the address field the pasted words are not shown but when I save this they are there.

**Comment by dobladov** [comment] 2018-09-04 10:01
I think the problem might be that the copied text _contained_ some CSS with it, @karindr can you tell us the resource with the problem and from where did you copied the address?

**Comment by karindr** [comment] 2018-09-04 10:34
At the moment it works. When it occurs next time I will tell you my source of copying.

**Comment by karindr** [comment] 2018-09-04 10:48
Example:
Republic of Argentina # 28, 
Historical Center, Mexico City. CP 06020 
copied from
https://www.gob.mx/sep/en#1053

**Comment by karindr** [comment] 2018-09-06 11:00
When I copy from google maps with the copy function this happens too.

**Comment by karindr** [comment] 2018-09-10 09:44
Copying from nearly every webpage does not work.

**Comment by dobladov** [comment] 2018-09-10 11:12
Copying and pasting from both websites seems to work, can you take a screenshot of show in another way how is failing?, also which browser are you using? @karindr 

![paste](https://user-images.githubusercontent.com/1938043/45294216-ec0e8b80-b4fa-11e8-9cac-6d3313c15815.gif)
---
![paste2](https://user-images.githubusercontent.com/1938043/45294218-ed3fb880-b4fa-11e8-9b03-e2439b06a882.gif)

**Comment by karindr** [comment] 2018-09-11 06:55
OK, this time copying from Google maps worked. 

I am using Chrome.

**Comment by literarymachine** [comment] 2018-09-11 07:47
> OK, this time copying from Google maps worked.

Since neither @dobladov nor I can reproduce this, we'll just have to keep an eye on this. If it occurs again, please list the steps to reproduce as exact as possible (e.g. highlight with mouse, copy with CTRL-C, paste into field XY using CTRL-V etc).

**Comment by karindr** [comment] 2018-09-11 07:51
Copying from here does not work:
https://www.usmd.edu/contact/

**Comment by karindr** [comment] 2018-09-11 07:53
This time the copied words are shown, but I can't delete in this line. (This is what I do when the system is not making any suggestions, normally it works.)

**Comment by dobladov** [comment] 2018-09-11 08:13
Like @literarymachine mentioned I can't recreate the issue, this is using Chrome and it seems to work properly.

![baltimore](https://user-images.githubusercontent.com/1938043/45346976-28012980-b5ab-11e8-8548-a2df484559ef.gif)

**Comment by literarymachine** [comment] 2018-09-11 08:29
> Copying from here does not work:
> https://www.usmd.edu/contact/

Please be specific, as I wrote above:

> list the steps to reproduce as exact as possible (e.g. highlight with mouse, copy with CTRL-C, paste into field XY using CTRL-V etc).

We cannot reproduce this in any way.

**Comment by karindr** [comment] 2018-09-11 08:39
I will be specific but for the last 2 entries, it worked as it should.

**Comment by karindr** [comment] 2018-09-11 11:03
„Add“ -> „Organisation“
Fill in „Website“. 
Select „Organisation type“ „Other“
Fill in „Name”, fill in “Description”
Chose Tag.
Selected “Primary Educational Sector”
„Select Country“ „United States“, „Select Region“ „Washington“.
Paste in “Address” “110 Legislative Building
Olympia, WA 98504-0600” by using Strg V, copying with Strg C from http://leg.wa.gov/legislature/pages/contactus.aspx
Nothing is shown in the field.
Click on “Publish” and open the entry by clicking on the pen icon, the entered address is shown. Now I can delete some characters until a suggestion is made, this time no suggestion fits so I get a new address from google.maps. Now it works.

I entered 2 new test entries with the same phenomenon:
https://oerworldmap.org/resource/urn%3Auuid%3A4fe35d62-37fd-4a7d-915c-145f21268414
https://oerworldmap.org/resource/urn%3Auuid%3A20696364-1261-41d6-8daa-7cee11f46208

Once @trugwaldsaenger stood besides me and saw the strange pasting and nothing appears thing. But even for me in my browser, it is not 100% reproducable. Very strange!

**Comment by karindr** [comment] 2018-09-24 09:10
I now had the same thing at home with my mac and firefox: I pasted the address, nothing appeared. I saved the address was there.

**Comment by dobladov** [comment] 2019-04-11 10:11
We tried to replicate the issue multiple times, even with the user in person but we couldn't recreate the problem, it could be an error related to the browser of the user.
Since nobody else seems to have the problem we are closing the issue.

**Closed by dobladov** 2019-04-11 10:11 UTC
Labels: bug, teammeeting_180927
