### ISSUE TITLE
When I first set the country filter and then the project filter the country filter is disabled

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1256] opened 2017-06-26 10:27 UTC

**Comment by literarymachine** [comment] 2017-06-26 10:32
> When I first set the country filter and then the project filter the country filter is enabled

This is expected behavior! Are you saying filters should be removed when another one is selected. We can also discuss details on our Slack channel by the way!

**Comment by literarymachine** [comment] 2017-06-26 10:50
Also see https://github.com/hbz/oerworldmap/issues/447#issuecomment-155828866.

**Comment by karindr** [comment] 2017-06-27 08:25
For example: Choosing Germany by setting the country filter to Germany (439 results). Then I want to see the organisations in Germany and click on the filter button organisation and get all organisations of the world (798). This is not like expected, is it?

**Comment by literarymachine** [comment] 2017-06-27 09:13
> This is not like expected, is it?

No! But the issue reads "When I first set the country filter and then the project filter the country filter is enabled", which should probably be "disabled". This is a duplicate of #1255, no? Sorry, but the issue titles get me confused as to what it really is about.

**Comment by karindr** [comment] 2017-06-27 09:29
Sorry, my fault in the title! Both issues are closely related. 

Here the problem is that it seems to be important to click at the filter buttons in the right order: First the type filter button and then the country filter. Nobody except us will ever understand this!

**Comment by literarymachine** [comment] 2017-06-27 09:32
> First the type filter button and then the country filter. Nobody except us will ever understand this!

I agree! The type filter is superordinate to all others, and the UI does not suggest this nor does it really make sense.

**Comment by literarymachine** [comment] 2018-07-31 13:45
Fixed in https://github.com/hbz/oerworldmap-ui/commit/8c9ed25599821367c13121f491dab72c32768564

**Closed by literarymachine** 2018-07-31 13:45 UTC
Labels: bug, working
