### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#902] opened 2016-10-17 06:45 UTC
When trying to register on the production system I receive following error message:
![161017_registration](https://cloud.githubusercontent.com/assets/6639965/19427691/e257f45a-9445-11e6-99dc-9d96cf07bb6e.JPG)

**Comment by drrobertfarrow** [comment] 2016-10-17 09:21
Hi Jan - could this be because it is already in the database? 
![screen shot 2016-10-17 at 10 25 02](https://cloud.githubusercontent.com/assets/10849418/19432202/71b76e66-9453-11e6-97ba-d92d892f361b.png)
base?

**Comment by trugwaldsaenger** [comment] 2016-10-17 10:09
Hi Rob, thanks for checking. That`s a good point. I thought I checked it in advance, but seemingly I did not...

So I tried it again, this time with jn@anisation.org and it worked. So the good news is: It does not seem as if we have a general issue!

But: The original complain came from Rory, who failed to lock in ("Failed to add rory@athabascau.ca"). I checked his address as well (twice), but it is not on the list. Nevertheless, Rory seems to receive the same error message as if we was already in the system....

**Comment by trugwaldsaenger** [comment] 2016-10-17 10:28
My assumption now is that
1) Rorys mail address was added to the system in the past
2) For some reason it is not displayed in our list
3) Nevertheless, this is blocking his new registration!

**Comment by literarymachine** [comment] 2016-10-17 15:17
> 1) Rorys mail address was added to the system in the past

The email address was used two days ago to sign up.

> 2) For some reason it is not displayed in our list

The verification link was not clicked, thus the sign up was not completed.

> 3) Nevertheless, this is blocking his new registration!

It is, but this is expected behavior. Registration is working as it should, closing.

**Comment by literarymachine** [comment] 2016-10-17 15:26
> So I tried it again, this time with jn(at)anisation(dot)org and it worked!

@trugwaldsaenger did you receive a verification delivered to this address. Because it currently seems like sending mails via our server is not working. This is not an issue of the OER World Map software, though. @philboeselager could you take a look. The configuration in `conf/application.conf` used to work.

**Comment by literarymachine** [comment] 2016-10-17 16:02
@philboeselager never mind. While our code was unchanged, the upgrade to apache commons email 1.4 for some reason resulted in emails not being sent Fixed in https://github.com/hbz/oerworldmap/pull/903/commits/0242f70df1a3f54e617cc36073bfb575128a903a#diff-fdc3abdfd754eeb24090dbd90aeec2ceL20, but we will have to investigate why exactly this happened.

**Comment by acka47** [comment] 2016-10-18 09:57
Though it took quite some time until the registration email arrived, this probably was due to hbz-internal procedures. Registration (once again) works as expected. Closing.

**Closed by acka47** 2016-10-18 09:57 UTC
Labels: bug, review
