### ISSUE TITLE
Some UK Counties (=subnational entities) remain white despite included Pins

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1555] opened 2018-05-29 14:01 UTC
![grafik](https://user-images.githubusercontent.com/6639965/40663679-8053e428-6359-11e8-95d1-41f30c5baa3d.png)

I would expect, that every county, which carries a pin should be at least slightly green...

**Comment by literarymachine** [comment] 2018-05-29 18:27
Duplicate of #1484. For pins, coordinates are needed. For the coloring, the region has to be specified (so that nobody is forced to give an exact location to be counted in the choropleth map). For the UK, a lot of entries [are missing the region but have a pin](https://oerworldmap.org/country/gb?q=_exists_:about.location.geo%20AND%20_missing_:about.location.address.addressRegion). This has to be fixed on the data level by setting the region.

**Comment by literarymachine** [comment] 2019-05-20 12:46
Fixed this on the data level on beta: https://beta.oerworldmap.org/country/gb

**Comment by literarymachine** [comment] 2019-05-23 14:51
Data fixed on production.

**Closed by literarymachine** 2019-05-23 14:51 UTC
Labels: review
