### ISSUE TITLE
Values of policy field "scope" appears in Portuguese when German language is selected

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1914] opened 2020-06-10 09:16 UTC
![grafik](https://user-images.githubusercontent.com/6639965/84249880-a043a880-ab0b-11ea-8a79-03cb3b2e5d3e.png)

Maybe the German values are missing, when English is selected values are displayed in English

**Comment by literarymachine** [comment] 2020-08-11 09:17
The problem is quite trivial; there is an error in the source file where Portuguese labels are configured under the `de` language tag. See e.g.

```
{
      "@id": "https://oerworldmap.org/assets/json/policies.json#dedicated",
      "@type": "Concept",
      "name": [
        {
          "@language": "en",
          "@value": "Dedicated OE/OER policy"
        },
        {
          "@language": "pt",
          "@value": "Dedicated OE/OER policy"
        },
        {
          "@language": "de",
          "@value": "Política exclusivamente de EA/REA"
        }
      ]
    }
```

https://github.com/hbz/oerworldmap-ui/blob/master/src/json/policies.json#L19

**Comment by literarymachine** [comment] 2020-08-17 12:30
On beta, see https://beta.oerworldmap.org/resource/?filter.about.%40type=%22Policy%22:

![image](https://user-images.githubusercontent.com/149825/90396225-234a2780-e096-11ea-80a1-dad6fbaca75f.png)

**Comment by trugwaldsaenger** [comment] 2020-08-18 10:47
+1 I can confirm, that the scope values are in German, when German language is selected.

**Comment by trugwaldsaenger** [comment] 2020-08-18 10:48
But I failed to switch language on beta. When trying to switch to English or to Portuguise following popup appears:
![grafik](https://user-images.githubusercontent.com/6639965/90504225-0f173080-e151-11ea-80f5-055273575eae.png)

**Comment by literarymachine** [comment] 2020-08-27 09:20
Unfortunately this is not fixed:

![image](https://user-images.githubusercontent.com/149825/91422069-f98fbe00-e856-11ea-8622-3eeef6839608.png)

@dr0i something must have gone wrong in the merging / deployment process, but I don't know what yet.

**Comment by literarymachine** [comment] 2020-08-27 10:22
All fine now, perhaps I had a local caching issue:

![image](https://user-images.githubusercontent.com/149825/91430921-e2090300-e85f-11ea-8d80-043a9db63e1f.png)

Closing.

**Closed by literarymachine** 2020-08-27 10:22 UTC
Labels: P2 - Should
