### ISSUE TITLE
Add new fields to json export for production of oer-Atlas, 2. edition

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1358] opened 2017-10-12 10:12 UTC
According to this list:
https://docs.google.com/document/d/1ITNe1WLl52VYHrXLZ2RH5pjx_AEUFqTB8IT-0IL_Aes/edit#heading=h.dph175gn3dpl
Talked to @philboeselager about this.

**Comment by literarymachine** [comment] 2017-10-12 10:19
Duplicate of #1357?

**Comment by karindr** [comment] 2017-10-12 10:30
No, one is about json and the other about csv. I thought you want to have two seperate issues for these two exports.

**Comment by literarymachine** [comment] 2017-10-12 10:58
Ah sorry, my bad!

**Comment by philboeselager** [comment] 2017-10-12 11:23
As discussed with @literarymachine , we will not customize the code fitting this one specific case. Instead, we will enable "export all fields" for lists so that individual resource export and resource list export provide the same fields.

If necessary, we can implement Python scripts to sort out unwanted fields from this "all fields export".

**Comment by literarymachine** [comment] 2017-10-26 13:14
I just realized that always fetching all fields works well for exports, but results in way too large HTML responses. Reopening. @philboeselager I already have something in mind how to fix this so I'll give it a try.

**Closed** 2017-11-13 14:26 UTC
Labels: review
