### ISSUE TITLE
Strange horizontal and vertical lines on the map

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#915] opened 2016-11-01 15:35 UTC
Reported by @drrobertfarrow: I am seeing some strange horizontal and vertical lines on the map at the moment (see attached).  I'm using Chrome on a Mac in case that matters.
![screen shot 2016-11-01 at 11 19 29](https://cloud.githubusercontent.com/assets/149825/19895453/244931be-a051-11e6-90d3-651c3aeab0f6.png)

**Comment by j0hj0h** [comment] 2016-11-03 15:38
I had the same glitches, but they are gone. Possibly fixed by the last Chrome update on November 1st. @drrobertfarrow can you check your Chrome version, potentially update to the last and see if the problem is gone? I'm on version 54.0.2840.87 now.

**Comment by drrobertfarrow** [comment] 2016-11-03 15:52
Sorry - I am still seeing them.... I have also tried to clear the cache

New screengrabs:

![screen shot 2016-11-03 at 11 50 01](https://cloud.githubusercontent.com/assets/10849418/19973527/d819cc38-a1bb-11e6-9634-7ef036db68f6.png)
![screen shot 2016-11-03 at 11 49 51](https://cloud.githubusercontent.com/assets/10849418/19973528/d82085be-a1bb-11e6-823f-1d50f1eb9e4b.png)

**Comment by literarymachine** [comment] 2016-11-03 16:12
@drrobertfarrow which chrome version are you on?

**Comment by drrobertfarrow** [comment] 2016-11-03 20:04
I went to check version and this started an automatic update of my Chrome.  After this restarted the problem seems to have gone!  So I think you may have been right about needing to update.

Maybe we should add something to the FAQ about encouraging people to update their browser if they're experiencing display errors...?

**Closed by drrobertfarrow** 2016-11-03 20:04 UTC
Labels: bug
