### ISSUE TITLE
Can't save Maths as subject on production

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1167] opened 2017-04-04 09:12 UTC
It is this entry:
https://oerworldmap.org/resource/urn:uuid:c7cc7141-64bc-4d2e-a278-b56eaec058b9

When I choose "Maths" and want to save I get this:

com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: instance failed to match all required schemas (matched only 1 out of 2)
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Service/properties/about/items"}
    instance: {"pointer":"/about/2"}
    domain: "validation"
    keyword: "allOf"
    matched: 1
    nrSchemas: 2
    reports: {"/definitions/Service/properties/about/items/allOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/Link"},"instance":{"pointer":"/about/2"},"domain":"validation","keyword":"required","message":"object has missing required properties ([\"@id\",\"@type\"])","required":["@id","@type"],"missing":["@id","@type"]}],"/definitions/Service/properties/about/items/allOf/1":[]}
---  END MESSAGES  ---

**Comment by literarymachine** [comment] 2017-04-04 09:17
> When I choose "Maths" and want to save I get this:

Assuming you mean `Mathematics`, this is a duplicate of #1140.

**Comment by karindr** [comment] 2017-04-04 09:31
Yes, Mathematics. But this time it is on production and this is new because I have entered a lot of times Mathematics last year.

**Comment by literarymachine** [comment] 2017-04-04 09:32
>  last year.

Exactly ;-)

**Comment by literarymachine** [comment] 2017-04-04 11:47
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:e6f63d1b-987e-454d-bd6c-e2fc0ae2f6e0

**Comment by acka47** [comment] 2017-04-04 13:17
+1

**Closed** 2017-04-04 14:09 UTC
Labels: bug, duplicate, review
