### ISSUE TITLE
Sort subjects (educational fields) according to ISCED

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#940] opened 2016-11-18 11:11 UTC
Subjects should be sorted on the displayed side as well as in the template according to ISCED order

see page 15 http://www.uis.unesco.org/Education/Documents/isced-fields-of-education-training-2013.pdf

**Comment by literarymachine** [comment] 2016-11-18 11:56
Related to and/or duplicate of #626 and #745.

**Comment by literarymachine** [comment] 2016-12-05 17:51
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:851aa8bb-0076-434a-a307-6ae57d27f3ac or add a `Service` and see the drop down for subjects.

**Comment by karindr** [comment] 2016-12-06 10:12
Great to have the hierarchy shown!

But there are the duplicated fields missing see S. 18
http://www.uis.unesco.org/Education/Documents/isced-fields-of-education-training-2013.pdf
01 education and 011 education we have only 01 education, same for 
06 Information and Communication Technologies and 061 Information and Communication Technologies we have only 06.
And again on the next level there is
042 law and 0421 law we have only 042 law
same for 082 ff. and 104
Is this a problem @acka47?

**Comment by acka47** [comment] 2016-12-06 11:21
I removed these levels intentionally when creating the SKOS version as it seems to me to be bad design (just so to have different levels shown at the right place when presented as a table ).

**Comment by karindr** [comment] 2016-12-06 12:02
Then +1.

**Closed** 2016-12-06 12:48 UTC
Labels: enhancement, review
