### ISSUE TITLE
Production system down

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#730] opened 2016-06-30 05:14 UTC
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.
Apache/2.4.10 (Linux/SUSE) Server at oerworldmap.org Port 443

**Comment by literarymachine** [comment] 2016-06-30 07:19
[error] a.a.ActorSystemImpl - Uncaught error from thread [play-akka.actor.default-dispatcher-1256] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
    java.lang.OutOfMemoryError: Metaspace
            at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_31]
            at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_31]
            at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_31]
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[na:1.8.0_31]
            at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_31]
    java.lang.OutOfMemoryError: Metaspace
            at java.lang.ClassLoader.defineClass1(Native Method)
            at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
            at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
            at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            at Routes$.documentation(routes_routing.scala:216)
            at Routes$.documentation(routes_routing.scala:17)
            at views.html.defaultpages.devNotFound$.apply(devNotFound.template.scala:134)
            at views.html.defaultpages.devNotFound$$anonfun$f$1.apply(devNotFound.template.scala:159)[ERROR] [06/30/2016 02:37:33.125] [play-akka.actor.default-dispatcher-1256] [ActorSystem(play)] Uncaught err
    or from thread [play-akka.actor.default-dispatcher-1256] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
    java.lang.OutOfMemoryError: Metaspace
            at java.lang.ClassLoader.defineClass1(Native Method)
            at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
            at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
            at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            at Routes$.documentation(routes_routing.scala:216)
            at Routes$.documentation(routes_routing.scala:17)
            at views.html.defaultpages.devNotFound$.apply(devNotFound.template.scala:134)
            at views.html.defaultpages.devNotFound$$anonfun$f$1.apply(devNotFound.template.scala:159)
            at views.html.defaultpages.devNotFound$$anonfun$f$1.apply(devNotFound.template.scala:159)
            at play.api.GlobalSettings$class.onHandlerNotFound(GlobalSettings.scala:173)
            at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onHandlerNotFound(JavaGlobalSettingsAdapter.scala:41)
            at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onHandlerNotFound$2.apply(JavaGlobalSettingsAdapter.scala:41)
            at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onHandlerNotFound$2.apply(JavaGlobalSettingsAdapter.scala:41)
            at scala.Option.getOrElse(Option.scala:120)
            at play.core.j.JavaGlobalSettingsAdapter.onHandlerNotFound(JavaGlobalSettingsAdapter.scala:41)
            at play.api.GlobalSettings$$anonfun$1.apply(GlobalSettings.scala:80)
            at play.api.GlobalSettings$$anonfun$1.apply(GlobalSettings.scala:80)
            at play.api.mvc.Action$.invokeBlock(Action.scala:556)
            at play.api.mvc.Action$.invokeBlock(Action.scala:555)
            at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
            at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
            at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
            at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
            at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
            at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
    
            at views.html.defaultpages.devNotFound$$anonfun$f$1.apply(devNotFound.template.scala:159)
    
            at play.api.GlobalSettings$class.onHandlerNotFound(GlobalSettings.scala:173)
            at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onHandlerNotFound(JavaGlobalSettingsAdapter.scala:41)
            at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onHandlerNotFound$2.apply(JavaGlobalSettingsAdapter.scala:41)
            at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onHandlerNotFound$2.apply(JavaGlobalSettingsAdapter.scala:41)
            at scala.Option.getOrElse(Option.scala:120)
            at play.core.j.JavaGlobalSettingsAdapter.onHandlerNotFound(JavaGlobalSettingsAdapter.scala:41)
            at play.api.GlobalSettings$$anonfun$1.apply(GlobalSettings.scala:80)
            at play.api.GlobalSettings$$anonfun$1.apply(GlobalSettings.scala:80)
            at play.api.mvc.Action$.invokeBlock(Action.scala:556)
            at play.api.mvc.Action$.invokeBlock(Action.scala:555)
            at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518)
            at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
            at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
            at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
            at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
            at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)

**Comment by trugwaldsaenger** [comment] 2016-06-30 07:41
System is up again!

**Comment by philboeselager** [comment] 2016-06-30 08:34
For now, our server capacity is close to exhausted due to running old processes. As a first step, these will be stopped.

**Comment by literarymachine** [comment] 2016-06-30 08:37
:+1:

**Comment by literarymachine** [comment] 2016-06-30 08:38
9005 is currently productive and 9006 is beta.

**Comment by philboeselager** [comment] 2016-06-30 08:49
Free memory has increased from 16.5% to 48.2%.

9004 is still running (as a fallback) since its memory usage is only about 1.2%. We could stop that anyway.

I assume this issue to be solved for now.
@literarymachine : If you agree please feel free to close it.

**Comment by literarymachine** [comment] 2016-06-30 09:49
> I assume this issue to be solved for now.

Not quite yet. While it is good that our free memory has increased, the problem is that [the Metaspace area in memory is exhausted](https://plumbr.eu/outofmemoryerror/metaspace). From what I can see, activator seems to default to `-XX:MaxMetaspaceSize=256m`.

We should identify the cause for "either too many classes or too big classes being loaded to the Metaspace". It looks like there are [Memory leaks in development mode with play 2.3.4](https://github.com/playframework/playframework/issues/3799), which might also apply to `2.3.7`, the version we are using. Currently the app is actually deployed in development mode to avoid downtime because I am still frequently deploying smaller changes. We can either add ["-XX:MaxMetaspaceSize=512m" to java opts](https://github.com/playframework/playframework/issues/3799#issuecomment-142568870) or run in production mode.

**Comment by philboeselager** [comment] 2016-06-30 10:09
> From what I can see, activator seems to default to -XX:MaxMetaspaceSize=256m

That's really important. Where did you find that? We could even increase to "-XX:MaxMetaspaceSize=1024m" for now and run beta in production mode.

**Comment by literarymachine** [comment] 2016-06-30 10:12
> Where did you find that?

    ps aux|grep activator

512m should be enough, as [suggested above](https://github.com/playframework/playframework/issues/3799#issuecomment-142568870).

Will check out if everything runs smooth in production mode locally and if so use that on production by tomorrow!

**Comment by philboeselager** [comment] 2016-06-30 10:24
> ps aux|grep activator

Yes, that explains it. I didn't check that following our telephone talk.

> 512m should be enough, as suggested above.

If we leave it out completely Java default is "unlimited". If there's a specific reason not to do so, I would recommend to set a bigger amount since we have no experience on the long term behaviour of the triple store.

**Comment by literarymachine** [comment] 2016-06-30 10:33
> we have no experience on the long term behaviour of the triple store.

While this is true, the crash is supposedly not related to the triple store or our own code: ["Basically we are experiencing "out of memory" errors after a limited number of application reloads"](https://github.com/playframework/playframework/issues/3799#issue-53958504).

> If we leave it out completely Java default is "unlimited".

Can you check how to overwrite the default activator settings?

**Comment by literarymachine** [comment] 2016-06-30 11:05
> Will check out if everything runs smooth in production mode locally and if so use that on production by tomorrow!

If all paths on `conf/application.conf` are absolute, production mode should not be a problem as long as we use the external node.js framing service (which we currently do, anyways).

**Comment by philboeselager** [comment] 2016-06-30 14:20
> Can you check how to overwrite the default activator settings?

$ JAVA_OPTS="-Xms1024m -Xmx1024m -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=1024m" </path/to/activator> "run -Dhttp.port=9005"
(or 512m of course)

Obviously, there is no chance to re-set MaxMetaspaceSize to unlimited, once the default has been overridden by an application chain.

**Comment by literarymachine** [comment] 2016-06-30 14:35
> Obviously, there is no chance to re-set MaxMetaspaceSize to unlimited, once the default has been overridden by an application chain.

I see, ok then. I will either restart in production mode or with the above setting later today!

**Comment by literarymachine** [comment] 2016-06-30 16:11
Now running in production mode, closing.

**Closed by literarymachine** 2016-06-30 16:11 UTC
Labels: bug
