### ISSUE TITLE
Can't edit organization type

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1874] opened 2019-10-14 18:46 UTC
Trying to edit the organization type for URI `https://oerworldmap.org/resource/urn:uuid:c25253a7-b17b-4e58-9464-fd2e9ae4337b`, clicking on publish doesn't go anywhere. Button changes color to orange, when clicked, but seems not to be activated.

**Comment by acka47** [comment] 2019-10-15 08:02
Thanks for the report, Tel (and all the others). I am able to reproduce this bug.

**Comment by trugwaldsaenger** [comment] 2019-10-21 08:31
Yes, I cannot edit this entry as well. Might be something specific with this entry since I can edit other organisations.

**Comment by trugwaldsaenger** [comment] 2019-10-23 08:29
I was able to change edit the insitutional type. I assume @tamielbr and @acka47 can do so as well and close the issue!

**Comment by tamielbr** [comment] 2019-11-04 20:14
Seems like this one has a similar problem, still. Can't edit and publish - button changes color, but no effect. Tried with three different users and different machines:

https://oerworldmap.org/resource/urn:uuid:9a030999-4d38-44fa-879c-c7fa63925a77?

**Comment by literarymachine** [comment] 2019-11-05 08:29
Confirmed, this is also a schema issue related to the introduction of the `Policy` type.

**Closed** 2019-11-05 10:26 UTC
Labels: P1 - Must, bug, sprint19-october
