### ISSUE TITLE
Create controlled vocabulary for service types

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#305] opened 2015-08-05 08:57 UTC
See #303.

**Comment by acka47** [comment] 2015-11-09 15:46
I will start with a light SKOS scheme including the three concepts named in issuecomment adding "referatory".

**Comment by acka47** [comment] 2015-11-30 15:33
Duplicate of https://github.com/hbz/vocabs-edu/issues/25. Closing.

**Closed by acka47** 2015-11-30 15:33 UTC
Labels: 2 - Tasklog, task
