### ISSUE TITLE
Tag filter splits up connected tags

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#638] opened 2016-05-10 13:26 UTC
There are several tags which exist of two words connected with a hyphen:
* oer-funder
* oer-research

The search function allows filtering for tags, but makes several words out of every connected tag. For example it is possible to choose the tag "oer". In this case the results will contain results tagged as both "oer-funder" as well as "oer-research":

https://oerworldmap.org/resource/?q=&filter.about.tag=oer

**Comment by karindr** [comment] 2016-10-04 09:25
if I understand it correctly the problem is solved, isn't it?

**Comment by literarymachine** [comment] 2016-10-04 10:01
> if I understand it correctly the problem is solved, isn't it?

It is indeed. Closing.

**Closed by literarymachine** 2016-10-04 10:01 UTC
Labels: bug
