### ISSUE TITLE
Implement likes and lighthouses as sorting-mechanisms

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1539] opened 2018-05-16 13:20 UTC
# Problem desription
- result lists ordered by the number of likes or lighthouses can be shown by clicking on the orange buttons
- having clicked on "likes" I get a list, which is actually ordered according to the number of likes, but the our current version says, that it is ordered according to date
- currently it is not possible to sort a filtered list according to likes/lighthouses, neiter is it possible to filter the likes/lighhouse lists created with the orange buttons.

# Solution
- just include "number of likes", "number of lighthouses" as sorting criteria similar to the current used "date", "alphabet" and "relevance" (which is currently not available any longer)
- the orange buttons could be kept in order to highlight the availability of the functionality
- I guess this would be a rather common solution, for example Amazon allows to rank results according the average customer reviews

**Comment by literarymachine** [comment] 2018-05-16 15:08
> which is currently not available any longer

You mean relevance? It is only available when you entered a search because it makes no sense for fixed-term filters. It is actually even the default sorting when you enter a search term:

![image](https://user-images.githubusercontent.com/149825/40125642-b22f1658-592b-11e8-83a5-611bf4fa34c9.png)

**Comment by literarymachine** [comment] 2018-05-16 15:10
> just include "number of likes", "number of lighthouses" as sorting criteria similar to the current used 

Yeah, we can do that. But what the orange button additionally does is limit the search result to only those that actually have a lighthouse / likes. When adding a sort option, also entries without likes / lighthouses would show up (after those that actually have lighthouses / likes).

**Comment by karindr** [comment] 2018-05-17 11:12
> You mean relevance? It is only available when you entered a search because it makes no sense for fixed-term filters.

Why should it for example make no sense to sort a list of all german organisations by relevance? It makes sense.

In addition to this for the useres it is better if things are as simmilar as possible in differnt cases, so it is good if you always can sonrt by date, relevance and alphabeth.

**Comment by literarymachine** [comment] 2018-05-17 11:29
> Why should it for example make no sense to sort a list of all german organisations by relevance? It makes sense.

So, what would be the "relevance" here? All of the entries have exactly one `DE` in `location.address.addressCountry`, so they all are equally relevant. This goes for all "fixed term" queries such as classifications. Believe me, there is no relevance to sort on without a search term. Feel free to specify expected behavior here and discuss with @philboeselager if you don't.

> In addition to this for the useres it is better if things are as simmilar as possible in differnt cases, so it is good if you always can sonrt by date, relevance and alphabeth.

You can't sort by relevance if there is no relevance to sort on so it makes no sense to show that filter.

**Comment by literarymachine** [comment] 2018-05-17 11:36
Also see here the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/_queries_and_filters.html):

> When used in filtering context, the query is said to be a "non-scoring" or "filtering" query. That is, the query simply asks the question: "Does this document match?". The answer is always a simple, binary yes|no.

So, our filters do not result in any scoring, only search terms do.

**Comment by literarymachine** [comment] 2019-10-28 17:06
Fixed in https://github.com/hbz/oerworldmap-ui/pull/568

**Closed by literarymachine** 2019-10-28 17:06 UTC
