### ISSUE TITLE
Establish a new entry type “Open Educational Resource”

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1032] opened 2017-01-18 11:09 UTC
In the future it should be possible to link to single resources. When we will have more registered people that enter data as editors we will have some of them enter (single) resources as service. We had the case of somebody of an American college who entered a textbook as service. We decided to delete it but there should be a better solution to cases like this.

**Comment by karindr** [comment] 2017-01-24 11:30
Look at this service it is a collection of 3 resources and surely helpful. 
https://oerworldmap.org/resource/urn:uuid:73bdfa21-6831-45b5-9221-2d2b46d3f1b2
3 resources makes it worth being called a service in my opinion. But it would be good to have the possibility to enter single resources on the map too.

**Comment by literarymachine** [comment] 2017-03-02 15:28
On https://beta.oerworldmap.org/ there is now a new entry type called "Bookmark" that can be used that can be used to add a bookmark to external web pages to the OER World Map, see also https://github.com/hbz/oerworldmap/issues/1103#issuecomment-283684632.

Is this sufficient for this use case here as well?

**Comment by acka47** [comment] 2017-03-03 14:56
I think this is at least a good basis for this use case but we might adjust the terminology to have it also coverd. I suggest to use the term "Publication" instead of  "Bookmark". Then it would easily also cover this use case and we could add additional fields for describing a publication when needed.

**Comment by literarymachine** [comment] 2017-03-05 11:44
> I suggest to use the term "Publication" instead of "Bookmark". Then it would easily also cover this use case and we could add additional fields for describing a publication when needed.

Agreed. I used "Bookmark" because it seemed fit from the perspective of #1103, but "Publication" would also be fine there, wouldn't it? The only minor quibble might be a possible confusion with "Story", but I think we can get around this with e.g. a remark in the FAQs.

**Comment by karindr** [comment] 2017-03-07 10:48
I am not very happy with the new type used for these different cases:
1.	Publication i.e. blog post or article on a website we link to so we don’t need to copy the article to our website. This is a type related to our stories.
2.	OEResource on a Website or maybe a Website with some resources, to few resources to be classified as service. But this type is related to our services.
I don’t think it is a good idea to mix these both things!
What I had in mind with this issue was something like a type or subtype “singe resource” or/and “mini-service”.

**Comment by literarymachine** [comment] 2017-03-07 11:07
Ok. Maybe this is an issue for next week's team meeting then, because the title of this issue is "Establish a new entry type 'Resource'" which is what #1103 does.

**Comment by karindr** [comment] 2017-03-07 11:11
Ok. To make it more clear I changed the title to "Open Educational Resource". What i was talking about were examples like a textbook and a service with only three resources (meaning OER).

**Comment by literarymachine** [comment] 2017-03-15 09:45
Possibly duplicate of #114.

**Comment by literarymachine** [comment] 2017-03-16 15:56
For now, an OER is simply a bookmark as defined in #1103 with the additional fields `creator` and `dateCreated`. What we need is the possibility to add bookmarks to `Person`, `Organization` and all other entry types except Story. The actual name "bookmark" is yet to be confirmed.

**Comment by acka47** [comment] 2017-03-16 16:11
@literarymachine noted that we have to answer the question: In what ways can bookmarks/publications be linked to existing OER World Map entities?

Here are some possible relations:
- Person: 
  - (list of) publications by the person
  - bookmark of puplications the person is interested in
- Organization: 
  - (list of) publications by the organization
  - a policy document enacted by the organization
- Event: 
  - a report about the event
  - a recording of the event
- Project: 
  - project proposal
  - a project report
- Service: 
  - tutorial 
  - documentation

**Comment by acka47** [comment] 2017-03-16 16:14
We should not forget about the possibility of adding value to the bookmark function by automatically archiving resources relevant to the OER community. From https://github.com/hbz/oerworldmap/issues/1103#issuecomment-283970810:

> we should add automatic archiving of the bookmarked links as well "link decoration" to make the references more stable. See also http://robustlinks.mementoweb.org/about/.

**Comment by literarymachine** [comment] 2018-09-18 15:32
> Here are some possible relations:
> - Person: 
>   - (list of) publications by the person
>   - bookmark of puplications the person is interested in
> - Organization: 
>   - (list of) publications by the organization
>   - a policy document enacted by the organization
> - Event: 
>   - a report about the event
>   - a recording of the event
> - Project: 
>   - project proposal
>   - a project report
> - Service: 
>   - tutorial 
>   - documentation

We have a generic `publications` field for all of the above types. Also, we have the possibility to give the type `Learning resource (OER)` to a publication. Closing.

**Closed by literarymachine** 2018-09-18 15:32 UTC
Labels: story
