### ISSUE TITLE
"Recent Additions" section seems to be lost 

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#682] opened 2016-06-02 11:13 UTC
In our previous version we had the "Recent Additions" section, which showed new entries at one sight. This functionality is currently lost with version 1.1. I would propose including it again to the platform, but I´m not sure how to do it best. One solution could be to show it when the list view is activated but no other filter/search has been entered yet.

**Comment by literarymachine** [comment] 2016-06-08 12:38
I would not consider this a bug given the fact that @j0hj0h is implementing the designs discussed at the last meetings and in https://github.com/hbz/oerworldmap/issues/577#issuecomment-200319919. Maybe @formimkontext can come up with something, but I am unsure if it can make it into v1.1

**Comment by trugwaldsaenger** [comment] 2016-06-08 14:46
I agree that this is not a classical bug. But its not a feature as well ;-).  I guess we can learn from this, that we have to be careful with every new version that no existing functionality is lost, or at least that it is lost on purpose. I guess @formimkontext is the right person to look for a solution. If we do not manage to solve it for version 1.1, this will not be a problem.

**Comment by trugwaldsaenger** [comment] 2016-06-08 14:56
The issue seems to be familiar with #681 because they are both caused by the fact that within the new three column design we have no column any longer, which can act as a "homepage". My solution to this would be to include a another sliding column, which is fixed at the left side of the frame, which can act as a homepage, e.g. by including highligted news, the recently added section and also the #681 table. I think that we disussed this idea in Berlin, and I think that @j0hj0h did not like it very much, but I cannot remember why....

**Comment by philboeselager** [comment] 2016-06-21 12:10
+1 for not labelling this as a bug. It's more about re-enabling a feature which had been taken out by design.

Another idea: we could provide a "popup" (?) box called "News" that can easily be closed by clicking "X". This box should have a checkbox labelled "Do not show News at startup". Classic design.

**Comment by literarymachine** [comment] 2016-07-01 09:26
Fixed by 2af0e3446a610b54db16770bc3ecd0dc62ad28f8

**Closed by literarymachine** 2016-07-01 09:26 UTC
Labels: bug, deploy, v1.1
