### ISSUE TITLE
Include Award Badge/Icon to Profil Page

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1347] opened 2017-09-29 13:01 UTC
There should be a possibility to add Badges/Icons for entries (all types) which have won an award or something similar. Application for this would be manifold:
- UNESCO World Congress Good Practice examples
- OER Award 2016 & 2017
- OEC Award

The badge should be a small icon similar to the one of the OER-Award:
http://wp1025437.server-he.de/open-educational-resources/wp-content/uploads/sites/4/2015/09/oerde16_logo_award.png
though I guess it should be either square or round. The badges normally should be produced by institutions, which organize awards or similar.

At the beginning, upload of the badge in the backoffice would be sufficient. The badge should also serve like a tag, e.g. it should be possible to show all initiatives, which received a certain award. Profils should be able to collect several badges over time.

In the long run, the badge could also be included in our search algorythm as a proof of quality, but right now, the graphical implementation in the GUI would make a good start.

**Comment by karindr** [comment] 2017-10-05 08:51
The 14 winners of the OER Award 16 are marked with the tag "OER-Award 2016". The award logo is here https://open-educational-resources.de/wp-content/uploads/oerde16_logo_award.png
This would be a nice first case.

**Comment by literarymachine** [comment] 2017-10-05 09:27
> right now, the graphical implementation in the GUI would make a good start.

A pragmatic first approach that could be implemented fairly quickly would be:

- Add an [`award`](http://schema.org/award) field that only admins can set and which takes a plain URL
- Add a filter for this field
- Add translated labels for the URLs

The labels could go into a separate `.properties` file. The format would be like this:

    https\://open-educational-resources.de/wp-content/uploads/oerde16_logo_award.png = "OERde 16 Award".

We could then expand the concept later on.

**Comment by literarymachine** [comment] 2017-11-20 10:47
As discussed offline with @trugwaldsaenger `Organization`, `Service`, `Action`, `Event` and `WebPage` will get an `award` field as described in https://github.com/hbz/oerworldmap/issues/1347#issuecomment-334410976. At a later stage we can discuss a more elaborate mechanism, e.g. based on a SKOS vocab.

**Comment by trugwaldsaenger** [comment] 2017-11-20 11:43
@gandalfar: Would this be interesting for OEC as well?

**Comment by literarymachine** [comment] 2017-11-23 14:32
> This would be a nice first case.

On beta, where I assigned the [badges for the OER DE16 award](https://beta.oerworldmap.org/resource/?q=&filter.about.award=https%3A%2F%2Fopen-educational-resources.de%2Fwp-content%2Fuploads%2Foerde16_logo_award.png&filter.about.keywords=oer-award+2016). To assign a badge, look for the `Award` field at the bottom of the input form and input the URL of the badge image there. Use [this one](https://open-educational-resources.de/wp-content/uploads/oerde17_logo_award.png) for OER DE17. To add other badges, a human readable name should be [added](https://github.com/hbz/oerworldmap/pull/1393/files#diff-759a395366f699c0df1e7128acf31572R288).

**Comment by gandalfar** [comment] 2017-11-24 11:20
OEC would be interested in participating. If you provide specification for badges/icon we'll provide the graphic.

For Open Education Awards, we have different graphic each year. I assume you would like just a single one that can be used throughout the years for all the award winners?

**Comment by karindr** [comment] 2017-11-27 11:43
@gandalfar , for the OERaward there are different  grafics each year too. That will be no problem.

**Comment by karindr** [comment] 2017-11-27 11:50
Is there a possibility to avoid that the badge becomes so blurry? In the case of the OER Award you cant even read the name! 

Did we speak about the position? If the badge is as small as it is at the momnet it could be also in the same line as the lighthouse but on the right side.

**Comment by literarymachine** [comment] 2017-11-27 13:27
> Is there a possibility to avoid that the badge becomes so blurry? In the case of the OER Award you cant even read the name!

Since we are linking to an [existing image](https://open-educational-resources.de/wp-content/uploads/oerde16_logo_award.png) there is not much that we can do. Scaling down raster images has this effect.

> Did we speak about the position? If the badge is as small as it is at the momnet it could be also in the same line as the lighthouse but on the right side.

No, we did not yet. This is a first version ideally to be deployed in time for tonight's OER awards.

**Comment by trugwaldsaenger** [comment] 2017-12-11 19:37
> OEC would be interested in participating. If you provide specification for badges/icon we'll provide the graphic.

I guess, we are pretty flexible. @formimkontext: Could you please tell @gandalfar how to achieve best resutls?

> For Open Education Awards, we have different graphic each year. I assume you would like just a single one that can be used throughout the years for all the award winners?

No, one grafic per year will be perfectly fine!

**Comment by karindr** [comment] 2018-01-08 11:30
Interesting new development: A registered user from Spain added links to their website and a blogpost to them winning an award. That was not, what we were thinking of, but this also an interesting way to do it.
https://oerworldmap.org/resource/urn:uuid:15fdc244-c227-42a4-bf87-907c8a4fcc0f

Have a look at an example I built on beta: https://beta.oerworldmap.org/resource/urn:uuid:7650225d-82f3-4b68-b5b8-dc4ba9352fd9

1. I am only allowed to enter a URL in the award field. So I entered the URL of the article. The url is show, but not clickable. I am not allowed to enter a link in markdown. I think we should allow to enter a link to for example a post, about winning an award! Even in addition to displaying the icon for the award it makes sense. If only the Icon is displayed the visitor has to look up for himself, what this award was given for and from whom.
2. As other case I entered the url of the awards logo, but in the scaled down version there is nearly no information left. We should think of displaying the award logos bigger! And we have to change the help text to “Add the url of the logo of the award the organisation won.” 
4. Another solution could be to let only administrators enter the award so we can ask for smaller versions of the logos.

**Comment by trugwaldsaenger** [comment] 2018-01-08 15:26
> Another solution could be to let only administrators enter the award so we can ask for smaller versions of the logos.

+1

**Comment by gandalfar** [comment] 2018-01-09 18:55
Can you please provide specs for the graphics so we can send it to you, together with lists of winners?

**Comment by formimkontext** [comment] 2018-01-11 14:55
hey @gandalfar, we haven’t defined all specification so we are kind of flexibel. jpg or png with at least 144 ppi and svg or ai will be fine.

**Comment by literarymachine** [comment] 2018-01-11 15:06
> hey @gandalfar, we haven’t defined all specification so we are kind of flexibel. jpg or png with at least 144 ppi and svg or ai will be fine.

As a matter of fact, you can simply point us to an online version of the image for now! We will be refactoring the badges to be more sophisticated, but for now they are simply represented by the URL of their badge icon.

**Comment by karindr** [comment] 2018-01-22 11:51
The tool Turtlestitch got an award (OER17). Please make it possible, that we can give arwards to tools too.

**Comment by karindr** [comment] 2018-01-22 12:11
I tried a lot of times to find the oer17 winners all together and I gt only 7 in the list, see:
https://oerworldmap.org/resource/?q=&filter.about.award=https%3A%2F%2Foerworldmap.org%2Fassets%2Fimages%2Fbadge_preistraeger_100_2017.png&filter.about.location.address.addressCountry=DE
There are all 11 von the map with the badge.

**Comment by literarymachine** [comment] 2018-01-22 12:26
> There are all 11 von the map with the badge.

Yes, but they don't necessarily have `DE` as their location. Here are the ten that have the badge: https://oerworldmap.org/resource/?q=&filter.about.award=https%3A%2F%2Foerworldmap.org%2Fassets%2Fimages%2Fbadge_preistraeger_100_2017.png

As you mention above, I need to configure badges for tools, when that is done it will be all eleven.

**Comment by karindr** [comment] 2018-01-25 10:49
The problem is that the award filter is not shown very often. To see the filter I have to choose some other filters for example: DE, CH und AU. But I get only 8 winners by this. See:
https://oerworldmap.org/resource/?q=&filter.about.award=https%3A%2F%2Foerworldmap.org%2Fassets%2Fimages%2Fbadge_preistraeger_100_2017.png&filter.about.location.address.addressCountry=DE&filter.about.location.address.addressCountry=AT&filter.about.location.address.addressCountry=CH
Ah, I understand, the publications have no location (at the moment) and the tool is missing.
Will the award filter be visible in the new filter section from the beginning on? So that I dont have to make such detours?

**Comment by literarymachine** [comment] 2018-01-25 10:53
> Will the award filter be visible in the new filter section from the beginning on? So that I dont have to make such detours?

Yes, there will be a way to manually show the extended filters. In the meantime, @trugwaldsaenger always just [searches for *](https://oerworldmap.org/resource/?q=*) to show the extended filters without applying a filter.

**Comment by formimkontext** [comment] 2018-04-20 12:46
Award and badges are added to Item View and extended Filter on production. I think we can close this issue.

**Comment by literarymachine** [comment] 2018-04-23 18:48
Done for now, closing.

**Closed by literarymachine** 2018-04-23 18:48 UTC
