### ISSUE TITLE
Embedded video - add some padding?

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#868] opened 2016-09-19 07:34 UTC
When I look at a story that has video content (e.g. https://oerworldmap.org/country/gb#urn:uuid:9af4551b-8b8d-4be6-88af-1f055d450bf7) the embedded iFrame looks great and is working well.

However, if I wanted to go full screen to watch the video then it is hard for me to actually click on the button in the iFrame.  This is because it can be cut off by the edge of the browser window.  (I have attached a picture to try and illustrate this - I maximised the window size and you can still only see half of the button.)

![screen shot 2016-09-19 at 08 30 32](https://cloud.githubusercontent.com/assets/10849418/18624976/5a421b9e-7e43-11e6-87a2-d6ad81806dad.png)

This might be a fairly minor issue, and we should really check on a couple of machines to be sure as it could just be related to the way that Mac windows don't usually take up the whole screen.  It seems to result from the fact that our windows stack to the right and the 'full screen' button in the YouTube player is also on the right.  (I have only embedded content from YouTube so far.)

**Comment by j0hj0h** [comment] 2016-09-19 13:08
The problem is, that the YouTube embed code, as it comes from YouTube has a fixed width, while the column is flexible. Responsive YouTube embeds (adapting to the width of its container) are possible. That would mean to introduce some processing of the markdown content at some point. Have to talk about that with @literarymachine.

**Comment by dobladov** [comment] 2018-08-20 09:57
Fixed in the new UI, closing.

![image](https://user-images.githubusercontent.com/1938043/44333770-188d3580-a470-11e8-8f9f-71747c488c09.png)

**Closed by dobladov** 2018-08-20 09:57 UTC
