### ISSUE TITLE
Country champion login

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#439] opened 2015-11-10 13:26 UTC
As a country champion I want to login so that I can edit entries.

**Comment by formimkontext** [comment] 2015-11-30 19:22
drafts for the login-process 
![20151130-oer-world-map-login-1](https://cloud.githubusercontent.com/assets/15141949/11481851/fc430736-979f-11e5-97a3-edaae581c53a.jpg)
![20151130-oer-world-map-login-2](https://cloud.githubusercontent.com/assets/15141949/11481854/fc529ec6-979f-11e5-8a5c-4f6a02041400.jpg)
![20151130-oer-world-map-login-3](https://cloud.githubusercontent.com/assets/15141949/11481852/fc51ca6e-979f-11e5-95bd-8a5c2650425b.jpg)
![20151130-oer-world-map-login-4](https://cloud.githubusercontent.com/assets/15141949/11481855/fc52edae-979f-11e5-906f-84ac1fd825e6.jpg)
![20151130-oer-world-map-login-5](https://cloud.githubusercontent.com/assets/15141949/11481853/fc5288d2-979f-11e5-916b-1959e94eba35.jpg)

**Comment by j0hj0h** [comment] 2015-11-30 19:26
The user icon would link to the profile page. Further details concerning the one-time login mechanism, can be described in the password email if necessary. Slogan disappears, because someone logged in already joined.

**Comment by acka47** [comment] 2015-12-01 08:03
Looks good to me. I guess, the authentification window is browser-based so that it will be in the language one has chosen for the browser. Also, it probably won't read "user name and password for ftp://ftp"...

I've got one question: What happens when hovering over or clicking the person icon next to the "log out" button?

**Comment by j0hj0h** [comment] 2015-12-01 10:29
Authentication is browser based, yes. The text appearing instead of "ftp://ftp" can be configured. The user icon would link to the profile page. Also if profiles are not public yet it could just show the name, email address, photo and country championship. If we don't have profile editing features from the beginning, their could be an email link to request changes.

**Comment by literarymachine** [comment] 2015-12-06 17:00
#484 on https://beta.oerworldmap.org/. Added a couple more feedback steps to the workflow to make explicit what is going on, we can reduce these. Also, the styling is not final yet.

@acka47 @trugwaldsaenger @philboeselager @j0hj0h @formimkontext I added your work email addresses to the whitelist that allows to request one time passwords.

**Comment by acka47** [comment] 2015-12-07 09:18
+1 Works good. One minor suggestion:

- "it remains valid until you explicitly log out." -> I guess we can remove the "explicitely". It is clear that this means "hitting the log out" button.

**Comment by acka47** [comment] 2015-12-07 09:18
I had to do the testing in a separate browser, though, as I am facing problems logging out with user  `oerworldmap-9004` . Clicking the "Log out" button and confirming log out gives me a logout confirmation. Nonetheless, hitting "Continue" I am still logged in and can repeat the Log out process indefinitely. Logging out worked with my personal accout, though... Shall I make a separate issue for this?

**Comment by literarymachine** [comment] 2015-12-07 10:56
>  I am facing problems logging out with user oerworldmap-9004

Admin users can currently only log out by closing the browser window as they don't have tokens but fixed passwords. So this is expected behavior and the only thing we can do about it is (a) leave it as it is or (b) get rid of fixed admin accounts and assign the admin role to e.g. your account.

**Comment by literarymachine** [comment] 2015-12-07 10:58
> "it remains valid until you explicitly log out." -> I guess we can remove the "explicitely". It is clear that this means "hitting the log out" button.

Yes - I think we should go over all of the wording, including that of the token mail.

**Comment by literarymachine** [comment] 2015-12-07 11:18
@acka47 any thoughts on https://github.com/hbz/oerworldmap/pull/484#issuecomment-162442776? 

@trugwaldsaenger please add comments here at the issue, not at the pull request. Thanks!

**Comment by acka47** [comment] 2015-12-07 12:12
Re.https://github.com/hbz/oerworldmap/pull/484#issuecomment-162442776
+1 for staying on the page one logged in from.

**Comment by literarymachine** [comment] 2015-12-10 17:45
#491 on https://beta.oerworldmap.org/. @acka47 and @trugwaldsaenger feel free to test. Please note though that sometimes we have performance problems, e.g. when saving https://beta.oerworldmap.org/resource/urn:uuid:839897e6-178f-11e5-871b-3c970e4a9cbf. This is due to the fact that that resource is linked to https://beta.oerworldmap.org/resource/urn:uuid:277db498-9901-11e5-960c-e72e56893d88 which links to https://beta.oerworldmap.org/resource/urn:uuid:ff56c436-7e76-11e5-b76b-54ee7558c81f, which is huge. Thus a lot of write operations are triggered in that case. Maybe it would be best to create some test entries that do not link to the resources mentioned above.

**Comment by acka47** [comment] 2015-12-11 08:27
> Maybe it would be best to create some test entries that do not link to the resources mentioned above.

i adjusted the current test Event, see [this commit](https://github.com/hbz/oerworldmap/commit/5cc1de5aa14f252e12a7c57820958bfc8a4a3a09) from https://github.com/hbz/oerworldmap/pull/493.

**Comment by literarymachine** [comment] 2015-12-11 10:38
> i adjusted the current test Event, see this commit from #493.

In the context of the automatic schema tests, this doesn't really matter. What I meant is that when editing such a resource in the live system, things get slow. I updated the [test event](https://beta.oerworldmap.org/resource/urn:uuid:277db498-9901-11e5-960c-e72e56893d88) on beta.

**Comment by acka47** [comment] 2015-12-16 10:30
Here a list of the first things I notices using the web forms (feel free to open new issues for those or to tell me to do so). More might come in further comments...

*Dropdowns for selection*
- Clicking on the `Language` or `Country` drop down, I expect the cursor to be in the search field so I can start typing to find my language right away.
- Another nice enhancement would be to additionally enable search by the language's or country's name in its own language (e.g. typing "Deutsch" would give you "German").

*"Description" field*
- Line breaks aren't taken into account in the html. We will have to inform people that html tags may be used. Even better would be to enable people using markdown maybe with some format buttons (that add markdown markup, _not_ WYSIWYG).

*"Country Champion for" field*
- There should be a drop down list here to chose a country similar to the language selection list. (I typed in "Germany" and got an error.)

*"Lookup Coordinates" link*
- it would be nice when the link would point to a geo lookup with the address (street+locality) already typed into the search field

*Data is gone when submission introduces an error*
- Editing an "Organization" entry, I created an error within the "Country Champion for" field which was shown to me as JSON schema error after hitting the "submit" button. Thus, I hit the "back" button in the browser but didn't arrive at the web form. Hitting "Add organization" again led to an empty form, thus the whole work was deleted.

**Comment by acka47** [comment] 2015-12-16 10:38
*Input of alternate name to link to organization*

When I input an alternate name e.g. in the `memberOffield to link to an organization, the correct organization is suggested but only the alternate name is shown in the suggestion, e.g.:

![20151216_alternatename-input](https://cloud.githubusercontent.com/assets/160292/11838758/4d3e10f4-a3e9-11e5-9547-1762b32ea49e.png)

The full name should also be shown. We might always concatenate the full name and the alternate name here, e.g. "Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen, hbz".

**Comment by acka47** [comment] 2015-12-16 10:47
*Alternate names are not taken into accoutn for interlinking*

For example, I expect that https://beta.oerworldmap.org/resource/urn:uuid:7609a1b0-904b-4ed8-bb2b-48467ab09595 is suggested when typing "hbz" e.g. in a `memberOf` field.

**Comment by acka47** [comment] 2015-12-16 10:50
*Field names in web form don't match field names in profile*

E.g. in the web form for editing a "Person", I have got "Email" and "URL" while in the resulting profile it reads "Email Address" and "Personal Website". We will definitely have to align these.

**Comment by acka47** [comment] 2015-12-16 11:05
*Date entries*

We have several fields where dates are entered (for projects, events, articles). The format isn't clear and there is no way to select from a calendar. My suggestion for the beginning would be to add a grey `yyyy-mm-dd` in the filed itself to give some guidance.

**Comment by acka47** [comment] 2015-12-16 11:16
*Can not add mainEntityOf to Article*

Everything works fine with the autosuggest but I can't add any entity as `mainEntityOf` an Article.

**Comment by acka47** [comment] 2015-12-16 11:23
*"In Language" does not have autosuggest ofcontrolled values"

For Events, we have the "in Language" field. This should have the same dropdown for selection as the "Language" fields for text input.

**Comment by literarymachine** [comment] 2015-12-16 11:34
> "Country Champion for" field
>
>There should be a drop down list here to chose a country similar to the language selection list. (I typed in "Germany" and got an error.)

@j0hj0h already implemented that in aab9b33bf39338179bc6083aec21b884a492a02a which I forgot to deploy. Did that now.

**Comment by literarymachine** [comment] 2015-12-16 11:42
>"Lookup Coordinates" link
>
>it would be nice when the link would point to a geo lookup with the address (street+locality) already typed into the search field

The way http://www.latlong.net/ is built, this is not easily done. I suggest we don't put any additional effort into this but implement our own lookup-widget soon.

**Comment by literarymachine** [comment] 2015-12-16 11:46
> "Description" field
> 
>Line breaks aren't taken into account in the html. We will have to inform people that html tags may be used. Even better would be to enable people using markdown maybe with some format buttons (that add markdown markup, not WYSIWYG).

Added issue #496 for this.

**Comment by acka47** [comment] 2015-12-16 12:28
*Value of "Hashtag" field isn't shown in reource view*

See e.g. https://beta.oerworldmap.org/resource/urn:uuid:9b69f445-00e6-43c9-ad29-4e0a2265e645.

**Comment by acka47** [comment] 2015-12-16 12:33
*"Subject" entry for "Events"*

When I want to add a `subject` of an `Event` concepts from both classifications (ESC and ISCED-1997) are suggested, e.g.:

![20151216_event-subject](https://cloud.githubusercontent.com/assets/160292/11840863/71613672-a3f9-11e5-85ef-313ea5686b53.png)

Why don't we use the same functionality for adding a subject as for Services?

**Comment by literarymachine** [comment] 2015-12-16 12:43
> Dropdowns for selection

>Clicking on the Language or Country drop down, I expect the cursor to be in the search field so I can start typing to find my language right away.

@j0hj0h will fix this, see #497.

> Another nice enhancement would be to additionally enable search by the language's or country's name in its own language (e.g. typing "Deutsch" would give you "German").

As soon as we activate language negotiation (which only really makes sense when all of the UI is translated), the current language will always be used for the language lookup. I think we should not take any action until then.

**Comment by literarymachine** [comment] 2015-12-16 13:28
> Data is gone when submission introduces an error
>
>Editing an "Organization" entry, I created an error within the "Country Champion for" field which was shown to me as JSON schema error after hitting the "submit" button. Thus, I hit the "back" button in the browser but didn't arrive at the web form. Hitting "Add organization" again led to an empty form, thus the whole work was deleted.

See #498.

**Comment by literarymachine** [comment] 2015-12-16 13:37
>Alternate names are not taken into accoutn for interlinking
>
>For example, I expect that https://beta.oerworldmap.org/resource/urn:uuid:7609a1b0-904b-4ed8-bb2b-48467ab09595 is suggested when typing "hbz" e.g. in a memberOf field.

See #499.

**Comment by literarymachine** [comment] 2015-12-16 13:42
>Field names in web form don't match field names in profile
>
>E.g. in the web form for editing a "Person", I have got "Email" and "URL" while in the resulting profile it reads "Email Address" and "Personal Website". We will definitely have to align these.

See #500.

**Comment by literarymachine** [comment] 2015-12-16 13:56
> "In Language" does not have autosuggest ofcontrolled values"
>
>For Events, we have the "in Language" field. This should have the same dropdown for selection as the "Language" fields for text input.

See #501.

**Comment by literarymachine** [comment] 2015-12-16 13:59
> "Subject" entry for "Events"
>
>When I want to add a subject of an Event concepts from both classifications (ESC and ISCED-1997) are suggested, e.g.:

See #502.

**Comment by literarymachine** [comment] 2015-12-16 14:18
> Can not add mainEntityOf to Article
>
>Everything works fine with the autosuggest but I can't add any entity as mainEntityOf an Article. With mentions it works fine, though.

See #503.

**Comment by literarymachine** [comment] 2015-12-16 14:19
>Date entries
>
>We have several fields where dates are entered (for projects, events, articles). The format isn't clear and there is no way to select from a calendar. My suggestion for the beginning would be to add a grey yyyy-mm-dd in the filed itself to give some guidance.

See #504.

**Comment by literarymachine** [comment] 2015-12-16 14:21
> Value of "Hashtag" field isn't shown in reource view
>
>See e.g. https://beta.oerworldmap.org/resource/urn:uuid:9b69f445-00e6-43c9-ad29-4e0a2265e645.

See #505.

**Closed** 2016-01-27 11:24 UTC
Labels: 6 - Done, story
